const RAW_UPGRADES = [
  {
    id: "backpack",
    name: "Backpack",
    description: "Field pack. Equips to your loadout and lets you carry more salvage out of short runs.",
    verb: "Rig",
    cost: { scrap: 7, cloth: 2, wire: 1 },
    requires: { searches: 3, items: ["sewing_kit"] },
    effects: { grantItems: { backpack: 1 }, unlockSections: ["inventory"] },
  },
  {
    id: "rusty_knife",
    name: "Rusty Knife",
    description: "Early melee weapon. Grants Rusty Knife and +1 attack.",
    verb: "Bind",
    cost: { scrap: 5, cloth: 1 },
    materials: { sharp_metal: 1 },
    requires: { searches: 3 },
    effects: {
      attack: 1,
      grantItems: { rusty_knife: 1 },
      unlockSections: ["inventory"],
    },
  },
  {
    id: "shelter_stash",
    name: "Shelter Stash",
    description: "Opens Shelter and starts tracked food storage.",
    verb: "Secure",
    cost: { scrap: 12, wood: 3, cloth: 2 },
    requires: { searches: 3 },
    effects: {
      unlockSections: ["shelter"],
      discoverResources: ["food"],
    },
  },
  {
    id: "campfire",
    name: "Campfire",
    description: "Improves burn relief, keeps the room warm, and reveals Fuel.",
    verb: "Assemble",
    cost: { scrap: 18, wood: 3, fuel: 2, cloth: 1 },
    requires: { upgrades: ["shelter_stash"], burnUses: 1 },
    effects: {
      burnCondition: 5,
      discoverResources: ["fuel"],
      unlockSections: ["shelter"],
    },
  },
  {
    id: "basic_barricade",
    name: "Basic Barricade",
    description: "Base defense +2 and lower night damage.",
    verb: "Brace",
    cost: { scrap: 24, wood: 5, parts: 4, wire: 2 },
    requires: { upgrades: ["shelter_stash"] },
    effects: { defense: 2, nightMitigation: 0.35, unlockSections: ["shelter"] },
  },
  {
    id: "first_aid_rag",
    name: "First Aid Rag",
    description: "Consumable heal item. Reveals Medicine.",
    cost: { cloth: 2, medicine: 1 },
    requires: { searches: 5 },
    effects: {
      grantItems: { first_aid_rag: 1 },
      discoverResources: ["medicine"],
    },
  },
  {
    id: "food_search",
    name: "Simple Food Search",
    description: "Adds food search chance and one extra search roll.",
    cost: { scrap: 10, wood: 1 },
    requires: { upgrades: ["shelter_stash"] },
    effects: {
      searchFoodChance: 0.1,
      searchBonusRolls: 1,
    },
  },
  {
    id: "small_scavenge",
    name: "Small Scavenging Runs",
    description: "Opens Map and the Ruined Street route.",
    cost: { scrap: 28, food: 2, water: 2 },
    requires: { upgrades: ["backpack", "rusty_knife"] },
    effects: {
      unlockSections: ["map"],
      unlockZones: ["ruined_street"],
      expeditionLootBonus: 0.03,
    },
  },
  {
    id: "food_crate",
    name: "Food Storage",
    description: "Improves forage yield and stabilizes food flow.",
    cost: { scrap: 30, wood: 4, parts: 5, cloth: 2 },
    requires: { upgrades: ["food_search"] },
    effects: {
      forageYieldBonus: 0.14,
      discoverResources: ["food"],
    },
  },
  {
    id: "crafting_bench",
    name: "Crafting Bench",
    description: "Unlocks Inventory and improves parts and rare salvage.",
    cost: { scrap: 34, wood: 4, parts: 8, wire: 2 },
    requires: { upgrades: ["small_scavenge"] },
    effects: {
      searchPartChance: 0.06,
      rareLootBonus: 0.06,
      unlockSections: ["inventory"],
    },
  },
  {
    id: "pry_bar_tool",
    name: "Pry Bar",
    description: "Passive tool for sealed salvage, parts yield, and locked lanes.",
    verb: "Forge",
    cost: { scrap: 14, wood: 1, parts: 4, cloth: 1 },
    materials: { sharp_metal: 1 },
    requires: { upgrades: ["crafting_bench"] },
    effects: {
      grantItems: { pry_bar: 1 },
      searchPartChance: 0.08,
      salvageYieldBonus: 0.06,
      unlockSections: ["inventory"],
    },
  },
  {
    id: "hammer_tool",
    name: "Hammer",
    description: "Build tool for structural work and blunt weapon assembly.",
    verb: "Forge",
    cost: { scrap: 10, wood: 2, parts: 2, cloth: 1 },
    requires: { searches: 2 },
    effects: {
      grantItems: { hammer: 1 },
      unlockSections: ["inventory"],
    },
  },
  {
    id: "sewing_kit",
    name: "Sewing Kit",
    description: "Clothwork tool for packs, patched armor, and stitched repairs.",
    verb: "Stitch",
    cost: { scrap: 6, cloth: 3, wire: 1 },
    requires: { searches: 2 },
    effects: {
      grantItems: { sewing_kit: 1 },
      unlockSections: ["inventory"],
    },
  },
  {
    id: "salvage_hatchet",
    name: "Salvage Hatchet",
    description: "Passive tool for wood recovery, shelter work, and minor night resistance.",
    verb: "Forge",
    cost: { scrap: 16, wood: 3, parts: 3, cloth: 1 },
    materials: { sharp_metal: 1 },
    requires: { upgrades: ["crafting_bench"] },
    effects: {
      grantItems: { salvage_hatchet: 1 },
      forageYieldBonus: 0.08,
      nightMitigation: 0.15,
      unlockSections: ["inventory"],
    },
  },
  {
    id: "sharpening_stone",
    name: "Sharpening Stone",
    description: "Edgework tool for blades, spearheads, and cleaner melee prep.",
    verb: "True",
    cost: { scrap: 10, parts: 2, cloth: 1 },
    requires: { upgrades: ["crafting_bench"] },
    effects: {
      grantItems: { sharpening_stone: 1 },
      unlockSections: ["inventory"],
    },
  },
  {
    id: "carpenter_kit",
    name: "Carpenter Kit",
    description: "Repair tool. Adds repair power, maintenance support, and night resistance.",
    verb: "Assemble",
    cost: { scrap: 20, wood: 4, parts: 6, cloth: 1 },
    requires: { upgrades: ["crafting_bench", "salvage_hatchet"] },
    effects: {
      grantItems: { carpenter_kit: 1 },
      repairPower: 1,
      maintenance: 1,
      nightMitigation: 0.18,
      unlockSections: ["inventory"],
    },
  },
  {
    id: "hand_drill",
    name: "Hand Drill",
    description: "Repair and signal tool. Improves parts salvage and fix work.",
    verb: "Build",
    cost: { scrap: 22, wood: 2, parts: 7, wire: 2 },
    requires: { upgrades: ["crafting_bench", "pry_bar_tool"] },
    effects: {
      grantItems: { hand_drill: 1 },
      searchPartChance: 0.06,
      repairPower: 1,
      signalGain: 0.05,
      unlockSections: ["inventory"],
    },
  },
  {
    id: "weapon_rack",
    name: "Weapon Slot",
    description: "Unlocks weapon loadout and keeps melee gear ready.",
    cost: { scrap: 34, wood: 2, parts: 6, wire: 1 },
    requires: { upgrades: ["crafting_bench"] },
    effects: {
      weaponSlot: true,
      unlockSections: ["inventory"],
    },
  },
  {
    id: "nail_bat",
    name: "Nail Bat",
    description: "Mid-tier melee weapon. Grants Nail Bat and +1 attack.",
    verb: "Hammer",
    cost: { scrap: 18, wood: 5, parts: 3, wire: 1, cloth: 1 },
    requires: { upgrades: ["weapon_rack", "crafting_bench"] },
    effects: {
      grantItems: { nail_bat: 1 },
      attack: 1,
      unlockSections: ["inventory"],
    },
  },
  {
    id: "hunting_spear",
    name: "Hunting Spear",
    description: "Long-reach weapon. Grants Hunting Spear, +2 attack, and better expedition loot.",
    verb: "Shaft",
    cost: { scrap: 24, wood: 7, parts: 4, cloth: 2 },
    requires: { upgrades: ["weapon_rack", "watch_post"] },
    effects: {
      grantItems: { hunting_spear: 1 },
      attack: 2,
      expeditionLootBonus: 0.04,
      unlockSections: ["inventory"],
    },
  },
  {
    id: "armor_hooks",
    name: "Armor Slot",
    description: "Unlocks armor loadout and keeps protective gear ready.",
    cost: { scrap: 34, wood: 2, parts: 6, cloth: 2 },
    requires: { upgrades: ["crafting_bench"] },
    effects: {
      armorSlot: true,
      unlockSections: ["inventory"],
    },
  },
  {
    id: "patchwork_vest_kit",
    name: "Patchwork Vest",
    description: "Stitched armor. Grants Patchwork Vest and +1 defense.",
    verb: "Stitch",
    cost: { scrap: 18, cloth: 5, parts: 3, wire: 1 },
    requires: { upgrades: ["armor_hooks", "sewing_kit"] },
    effects: {
      grantItems: { patchwork_vest: 1 },
      defense: 1,
      unlockSections: ["inventory"],
    },
  },
  {
    id: "riot_padding_kit",
    name: "Riot Padding",
    description: "Armor upgrade. Grants Riot Padding and +1 defense.",
    verb: "Refit",
    cost: { scrap: 24, cloth: 5, parts: 6, wire: 1 },
    requires: { upgrades: ["armor_hooks", "watch_post"] },
    effects: {
      grantItems: { riot_padding: 1 },
      defense: 1,
      unlockSections: ["inventory"],
    },
  },
  {
    id: "watch_post",
    name: "Watch Post",
    description: "Major defense module. Adds defense, crew capacity, and safer routes.",
    cost: { scrap: 46, wood: 7, parts: 8, wire: 2 },
    requires: { upgrades: ["basic_barricade"] },
    effects: {
      defense: 3,
      survivorCap: 1,
      expeditionEncounterAdjust: -0.04,
      nightMitigation: 0.45,
    },
  },
  {
    id: "tripwire_grid",
    name: "Tripwire Grid",
    description: "Perimeter trap. Adds defense, coverage, and siege resistance.",
    cost: { scrap: 38, wood: 5, parts: 6, wire: 5 },
    requires: { upgrades: ["basic_barricade", "watch_post"] },
    effects: {
      defense: 2,
      siegeMitigation: 0.55,
      coverage: 0.2,
      nightMitigation: 0.25,
    },
  },
  {
    id: "ammo_press",
    name: "Ammo Press",
    description: "Unlocks Ammo and improves rare salvage.",
    cost: { scrap: 40, wood: 2, parts: 10, chemicals: 3 },
    requires: { upgrades: ["crafting_bench"] },
    effects: {
      discoverResources: ["ammo"],
      rareLootBonus: 0.04,
    },
  },
  {
    id: "repair_rig",
    name: "Repair Rig",
    description: "Raises repair output, maintenance support, and night stability.",
    cost: { scrap: 42, wood: 5, parts: 10, wire: 2 },
    requires: { upgrades: ["crafting_bench", "survivor_cots"] },
    effects: {
      repairPower: 2,
      maintenance: 1,
      nightMitigation: 0.12,
    },
  },
  {
    id: "rain_collector",
    name: "Rain Collector",
    description: "Passive water income and minor recovery.",
    cost: { scrap: 28, wood: 4, parts: 5, cloth: 2, wire: 2 },
    requires: { upgrades: ["shelter_stash"] },
    effects: {
      conditionRegen: 0.01,
      passive: { water: 0.015 },
      forageYieldBonus: 0.08,
    },
  },
  {
    id: "water_still",
    name: "Water Still",
    description: "Adds safer water income, water security, and slow recovery.",
    cost: { scrap: 28, wood: 5, parts: 6, fuel: 2, cloth: 2 },
    requires: { upgrades: ["rain_collector", "smokehouse"] },
    effects: {
      passive: { water: 0.01 },
      waterSecurity: 1,
      conditionRegen: 0.01,
    },
  },
  {
    id: "radio_rig",
    name: "Radio",
    description: "Unlocks Radio and increases trace depth.",
    cost: { scrap: 32, parts: 10, wire: 5, electronics: 3, fuel: 2 },
    requires: { upgrades: ["watch_post"] },
    effects: {
      unlockSections: ["radio"],
      radioDepth: 0.35,
      discoverResources: ["reputation"],
    },
  },
  {
    id: "battery_bank",
    name: "Battery Bank",
    description: "Supplies power for signal tools and stabilizes the radio stack.",
    cost: { scrap: 36, parts: 9, wire: 4, electronics: 3, fuel: 2 },
    requires: { upgrades: ["radio_rig"] },
    effects: {
      power: 3,
      signalGain: 0.08,
      maintenance: 1,
    },
  },
  {
    id: "signal_meter",
    name: "Signal Meter",
    description: "Signal tool. Improves trace gain and anomaly gain.",
    verb: "Tune",
    cost: { scrap: 24, parts: 6, wire: 4, electronics: 2 },
    requires: { upgrades: ["radio_rig", "crafting_bench"] },
    effects: {
      grantItems: { signal_meter: 1 },
      signalGain: 0.12,
      anomalyGain: 0.08,
      unlockSections: ["inventory"],
    },
  },
  {
    id: "flood_lights",
    name: "Flood Lights",
    description: "Boosts perimeter coverage and night resistance.",
    cost: { scrap: 34, parts: 8, wire: 5, electronics: 2, fuel: 3 },
    requires: { upgrades: ["watch_post", "radio_rig"] },
    effects: {
      coverage: 0.7,
      nightMitigation: 0.3,
    },
  },
  {
    id: "map_board",
    name: "Map",
    description: "Opens new zones and route planning.",
    cost: { scrap: 32, wood: 3, parts: 5, cloth: 2 },
    requires: { upgrades: ["small_scavenge"] },
    effects: {
      unlockSections: ["map"],
      unlockZones: ["burned_apartments", "abandoned_gas_station"],
    },
  },
  {
    id: "survivor_cots",
    name: "Survivor Recruitment",
    description: "Unlocks Crew and increases survivor capacity.",
    cost: { scrap: 36, wood: 6, food: 4, water: 3, cloth: 4 },
    requires: { upgrades: ["food_crate"] },
    effects: {
      unlockSections: ["survivors"],
      discoverResources: ["morale"],
      survivorCap: 2,
    },
  },
  {
    id: "smokehouse",
    name: "Smokehouse",
    description: "Improves food preservation and slow recovery.",
    cost: { scrap: 48, wood: 8, parts: 8, fuel: 4, cloth: 2 },
    requires: { upgrades: ["food_crate"] },
    effects: {
      forageYieldBonus: 0.22,
      conditionRegen: 0.01,
    },
  },
  {
    id: "trader_beacon",
    name: "Signal Beacon",
    description: "Strengthens signal gain and quiet-night mitigation.",
    cost: { scrap: 40, wood: 3, parts: 8, wire: 3, fuel: 4 },
    requires: { upgrades: ["radio_rig"] },
    effects: {
      signalGain: 0.18,
      nightMitigation: 0.35,
    },
  },
  {
    id: "scout_bike",
    name: "Scout Bike",
    description: "Unlocks deeper zones and improves expedition returns.",
    cost: { scrap: 52, parts: 14, fuel: 8, electronics: 2 },
    requires: { upgrades: ["map_board"] },
    effects: {
      unlockZones: ["flooded_tunnel", "hospital_wing"],
      expeditionLootBonus: 0.08,
      scoutBonus: 0.04,
    },
  },
  {
    id: "signal_decoder",
    name: "Signal Decoder",
    description: "Major radio upgrade. Deepens traces and reveals late mystery lanes.",
    cost: { scrap: 52, parts: 14, wire: 4, electronics: 4, relics: 2 },
    requires: { upgrades: ["radio_rig"], radioProgress: 2 },
    effects: {
      radioDepth: 0.75,
      signalGain: 0.12,
      secretProgress: 1,
    },
  },
  {
    id: "signal_cloak_kit",
    name: "Signal Cloak",
    description: "Late signal armor. Grants Signal Cloak and steadies radio-heavy runs.",
    verb: "Sew",
    cost: { scrap: 34, cloth: 6, wire: 4, electronics: 2, relics: 1 },
    requires: { upgrades: ["armor_hooks", "signal_decoder"], radioProgress: 3 },
    effects: {
      grantItems: { signal_cloak: 1 },
      coverage: 0.15,
      signalGain: 0.08,
      unlockSections: ["inventory"],
    },
  },
  {
    id: "auto_scavenger",
    name: "Auto Scavenger",
    description: "Small passive scrap and parts income plus better salvage routes.",
    cost: { scrap: 68, wood: 4, parts: 18, wire: 4, fuel: 6 },
    requires: { upgrades: ["survivor_cots", "watch_post"] },
    effects: {
      passive: {
        scrap: 0.02,
        parts: 0.008,
      },
      salvageYieldBonus: 0.08,
      scoutBonus: 0.04,
    },
  },
  {
    id: "faraday_mesh",
    name: "Faraday Mesh",
    description: "Heavy late defense against signal pressure and siege nights.",
    cost: { scrap: 64, parts: 18, wire: 8, electronics: 2, relics: 2 },
    requires: { upgrades: ["signal_decoder"] },
    effects: {
      defense: 4,
      nightMitigation: 0.85,
    },
  },
  {
    id: "relay_tap",
    name: "Relay Tap",
    description: "Boosts late radio depth, signal gain, and anomaly gain.",
    cost: { scrap: 66, parts: 20, wire: 7, electronics: 4, fuel: 8 },
    requires: { upgrades: ["trader_beacon"], radioProgress: 4 },
    effects: {
      radioDepth: 0.55,
      signalGain: 0.22,
      anomalyGain: 0.2,
    },
  },
  {
    id: "bunker_drill",
    name: "Bunker Drill",
    description: "Opens the bunker route and pushes secret progress.",
    cost: { scrap: 78, parts: 22, wire: 6, fuel: 12, relics: 3 },
    requires: { upgrades: ["signal_decoder"], secretProgress: 2 },
    effects: {
      unlockZones: ["hidden_bunker_entrance"],
      secretProgress: 1,
    },
  },
];

const UPGRADE_RULES = {
  backpack: {
    category: "tool",
    tier: "field",
    hours: 1,
    requiredTools: ["sewing_kit"],
    resultLabel: "Equip backpack",
  },
  rusty_knife: {
    category: "weapon",
    tier: "improvised",
    hours: 1,
    resultLabel: "Rusty Knife",
  },
  shelter_stash: {
    category: "build",
    tier: "starter",
    hours: 2,
    resultLabel: "Open shelter storage",
  },
  campfire: {
    category: "build",
    tier: "starter",
    hours: 2,
    resultLabel: "Warm shelter core",
  },
  basic_barricade: {
    category: "build",
    tier: "starter",
    hours: 3,
    requiredTools: ["hammer"],
    resultLabel: "Perimeter fence",
  },
  first_aid_rag: {
    category: "consumable",
    tier: "field",
    hours: 1,
    resultLabel: "First Aid Rag",
  },
  food_search: {
    category: "build",
    tier: "starter",
    hours: 2,
    resultLabel: "Food search loop",
  },
  small_scavenge: {
    category: "build",
    tier: "starter",
    hours: 2,
    resultLabel: "Ruined Street route",
  },
  food_crate: {
    category: "build",
    tier: "starter",
    hours: 2,
    requiredTools: ["hammer"],
    resultLabel: "Food storage",
  },
  crafting_bench: {
    category: "build",
    tier: "bench",
    hours: 3,
    requiredTools: ["hammer"],
    resultLabel: "Bench online",
  },
  pry_bar_tool: {
    category: "tool",
    tier: "field",
    hours: 3,
    resultLabel: "Pry Bar",
  },
  hammer_tool: {
    category: "tool",
    tier: "field",
    hours: 3,
    resultLabel: "Hammer",
  },
  sewing_kit: {
    category: "tool",
    tier: "field",
    hours: 3,
    resultLabel: "Sewing Kit",
  },
  salvage_hatchet: {
    category: "tool",
    tier: "field",
    hours: 3,
    resultLabel: "Salvage Hatchet",
  },
  sharpening_stone: {
    category: "tool",
    tier: "bench",
    hours: 2,
    resultLabel: "Sharpening Stone",
  },
  carpenter_kit: {
    category: "tool",
    tier: "workshop",
    hours: 4,
    requiredTools: ["hammer"],
    resultLabel: "Carpenter Kit",
  },
  hand_drill: {
    category: "tool",
    tier: "workshop",
    hours: 4,
    requiredTools: ["hammer"],
    resultLabel: "Hand Drill",
  },
  weapon_rack: {
    category: "build",
    tier: "starter",
    hours: 2,
    resultLabel: "Weapon slot",
  },
  nail_bat: {
    category: "weapon",
    tier: "bench-made",
    hours: 4,
    requiredTools: ["hammer"],
    resultLabel: "Nail Bat",
  },
  hunting_spear: {
    category: "weapon",
    tier: "bench-made",
    hours: 4,
    requiredTools: ["sharpening_stone"],
    resultLabel: "Hunting Spear",
  },
  armor_hooks: {
    category: "build",
    tier: "starter",
    hours: 2,
    resultLabel: "Armor slot",
  },
  patchwork_vest_kit: {
    category: "armor",
    tier: "stitched",
    hours: 4,
    requiredTools: ["sewing_kit"],
    resultLabel: "Patchwork Vest",
  },
  riot_padding_kit: {
    category: "armor",
    tier: "reinforced",
    hours: 4,
    requiredTools: ["sewing_kit"],
    resultLabel: "Riot Padding",
  },
  watch_post: {
    category: "build",
    tier: "defense",
    hours: 5,
    requiredTools: ["hammer", "carpenter_kit"],
    resultLabel: "Watch line",
  },
  tripwire_grid: {
    category: "build",
    tier: "defense",
    hours: 5,
    requiredTools: ["hammer", "hand_drill"],
    resultLabel: "Tripwire perimeter",
  },
  ammo_press: {
    category: "build",
    tier: "bench",
    hours: 4,
    requiredTools: ["hammer"],
    resultLabel: "Ammo press",
  },
  repair_rig: {
    category: "build",
    tier: "workshop",
    hours: 5,
    requiredTools: ["hand_drill", "carpenter_kit"],
    resultLabel: "Repair line",
  },
  rain_collector: {
    category: "build",
    tier: "starter",
    hours: 3,
    requiredTools: ["hammer"],
    resultLabel: "Water catch",
  },
  water_still: {
    category: "build",
    tier: "workshop",
    hours: 5,
    requiredTools: ["carpenter_kit"],
    resultLabel: "Clean water still",
  },
  radio_rig: {
    category: "build",
    tier: "signal",
    hours: 5,
    requiredTools: ["hand_drill"],
    resultLabel: "Radio line",
  },
  battery_bank: {
    category: "build",
    tier: "signal",
    hours: 6,
    requiredTools: ["hand_drill"],
    resultLabel: "Power reserve",
  },
  signal_meter: {
    category: "tool",
    tier: "signal",
    hours: 5,
    requiredTools: ["hand_drill"],
    resultLabel: "Signal Meter",
  },
  flood_lights: {
    category: "build",
    tier: "defense",
    hours: 6,
    requiredTools: ["hand_drill"],
    resultLabel: "Lit perimeter",
  },
  map_board: {
    category: "build",
    tier: "starter",
    hours: 2,
    requiredTools: ["hammer"],
    resultLabel: "Route board",
  },
  survivor_cots: {
    category: "build",
    tier: "starter",
    hours: 3,
    requiredTools: ["hammer", "sewing_kit"],
    resultLabel: "Crew beds",
  },
  smokehouse: {
    category: "build",
    tier: "starter",
    hours: 4,
    requiredTools: ["salvage_hatchet"],
    resultLabel: "Food preserve line",
  },
  trader_beacon: {
    category: "build",
    tier: "signal",
    hours: 5,
    requiredTools: ["signal_meter", "hand_drill"],
    resultLabel: "Signal beacon",
  },
  scout_bike: {
    category: "build",
    tier: "field",
    hours: 4,
    requiredTools: ["hammer"],
    resultLabel: "Deep route access",
  },
  signal_decoder: {
    category: "build",
    tier: "signal",
    hours: 6,
    requiredTools: ["signal_meter", "hand_drill"],
    resultLabel: "Decoder stack",
  },
  signal_cloak_kit: {
    category: "armor",
    tier: "signal",
    hours: 5,
    requiredTools: ["sewing_kit", "signal_meter"],
    resultLabel: "Signal Cloak",
  },
  auto_scavenger: {
    category: "build",
    tier: "workshop",
    hours: 6,
    requiredTools: ["hand_drill", "hammer"],
    resultLabel: "Auto salvage line",
  },
  faraday_mesh: {
    category: "build",
    tier: "signal",
    hours: 7,
    requiredTools: ["hand_drill", "signal_meter"],
    resultLabel: "Static shield",
  },
  relay_tap: {
    category: "build",
    tier: "signal",
    hours: 6,
    requiredTools: ["hand_drill", "signal_meter"],
    resultLabel: "Relay tap",
  },
  bunker_drill: {
    category: "build",
    tier: "late",
    hours: 8,
    requiredTools: ["hand_drill", "carpenter_kit"],
    resultLabel: "Bunker breach rig",
  },
};

export const UPGRADES = RAW_UPGRADES.map((upgrade) => ({
  ...upgrade,
  ...(UPGRADE_RULES[upgrade.id] || {}),
}));

export const UPGRADES_BY_ID = Object.fromEntries(UPGRADES.map((upgrade) => [upgrade.id, upgrade]));

export const ENEMIES = {
  walker: {
    id: "walker",
    name: "Walker",
    hp: 14,
    attack: [3, 5],
    reward: { scrap: 1 },
    description: "Slow, wet footsteps and no intention of stopping.",
    behavior: {
      defaultIntent: "grapple",
      intents: ["grapple", "lunge", "lunge"],
      gripChance: 0.35,
      gripPenalty: 0.18,
      aftermathThreat: 0.22,
      summary: "Likes to pin and drag the fight into a blunt mess.",
    },
    ascii: [
      "   .-.   ",
      "  (o o)  ",
      "  | O |  ",
      "  |   |  ",
      "  '~~~'  ",
    ],
  },
  screecher: {
    id: "screecher",
    name: "Screecher",
    hp: 18,
    attack: [4, 7],
    reward: { scrap: 1, ammo: 1 },
    description: "All throat, no restraint.",
    behavior: {
      defaultIntent: "shriek",
      intents: ["shriek", "lunge", "shriek"],
      shriekThreat: 0.45,
      shriekNoise: 0.6,
      retreatPenalty: 0.12,
      summary: "Builds pressure if you leave it alive or let it run.",
    },
    ascii: [
      "  .---.  ",
      " / x x \\ ",
      "|   ^   |",
      "|  ---  |",
      " \\\\___// ",
    ],
  },
  bloated_carrier: {
    id: "bloated_carrier",
    name: "Bloated Carrier",
    hp: 24,
    attack: [5, 8],
    reward: { fuel: 1, medicine: 1 },
    description: "Swollen with rot and useful things.",
    behavior: {
      defaultIntent: "rupture",
      intents: ["rupture", "lunge", "rupture"],
      deathBurst: { chemicals: 1, medicine: 1 },
      deathSplash: 3,
      summary: "Can burst open on death and splash anyone too close.",
    },
    ascii: [
      "  .---.  ",
      " ( ___ ) ",
      "| (___) |",
      "|  :::  |",
      " '-----' ",
    ],
  },
  stalker: {
    id: "stalker",
    name: "Stalker",
    hp: 22,
    attack: [6, 9],
    reward: { parts: 2 },
    description: "Quiet enough to feel unfair.",
    behavior: {
      defaultIntent: "ambush",
      intents: ["ambush", "lunge", "feint"],
      openerBonus: [2, 4],
      retreatPenalty: 0.2,
      summary: "Opens hard and punishes retreat if you lose the angle.",
    },
    ascii: [
      "  /\\_/\\\\ ",
      " ( o.o )",
      "  > ^ < ",
      " //   \\\\",
      "//     \\\\",
    ],
  },
  static_touched: {
    id: "static_touched",
    name: "Static-Touched",
    hp: 32,
    attack: [7, 11],
    reward: { relics: 1, parts: 2 },
    description: "Moves to a rhythm the city should have lost years ago.",
    behavior: {
      defaultIntent: "pulse",
      intents: ["pulse", "lunge", "pulse"],
      signalBurn: 0.35,
      moraleHit: 1,
      summary: "Builds static pressure and drains radio certainty mid-fight.",
    },
    ascii: [
      "  .:::.  ",
      " ( o o ) ",
      " /  ^  \\\\",
      "| '--' | ",
      " \\\\_=_// ",
    ],
  },
  relay_brute: {
    id: "relay_brute",
    name: "Relay Brute",
    hp: 40,
    attack: [9, 13],
    reward: { relics: 2, reputation: 1 },
    description: "Tower muscle wrapped in old transmitter mesh.",
    behavior: {
      defaultIntent: "crush",
      intents: ["crush", "lunge", "crush"],
      armor: 1,
      breachDamage: 1,
      summary: "Soaks weak hits and hits hard enough to damage shelter confidence.",
    },
    ascii: [
      " [#####] ",
      " (x x x) ",
      " /|===|\\\\",
      "/_|___|_\\\\",
      "  /   \\\\ ",
    ],
  },
};

export const ZONES = [
  {
    id: "ruined_street",
    name: "Ruined Street",
    description: "Crushed storefronts, dead traffic, loose copper in the walls.",
    risk: 1,
    hours: 2,
    encounterChance: 0.2,
    enemies: ["walker", "screecher"],
    loot: { scrap: [5, 9], wood: [2, 4], cloth: [1, 2], water: [0, 1], food: [0, 2], parts: [1, 2], fuel: [0, 1] },
    itemPool: ["pry_bar", "canned_beans"],
    itemChance: 0.16,
  },
  {
    id: "burned_apartments",
    name: "Burned Apartments",
    description: "Stacked smoke damage and private tragedies.",
    risk: 2,
    hours: 3,
    encounterChance: 0.28,
    enemies: ["walker", "stalker"],
    loot: { scrap: [7, 12], wood: [2, 5], cloth: [1, 3], water: [1, 2], food: [1, 3], parts: [2, 4], medicine: [0, 1] },
    itemPool: ["patchwork_vest", "bandage_roll"],
    itemChance: 0.2,
  },
  {
    id: "abandoned_gas_station",
    name: "Abandoned Gas Station",
    description: "The pumps are dry, but the tanks forgot that.",
    risk: 2,
    hours: 3,
    encounterChance: 0.3,
    enemies: ["walker", "bloated_carrier"],
    loot: { scrap: [4, 8], water: [0, 1], fuel: [2, 5], parts: [1, 3], chemicals: [0, 1] },
    itemPool: ["fuel_cell", "transit_pistol"],
    itemChance: 0.2,
  },
  {
    id: "flooded_tunnel",
    name: "Flooded Tunnel",
    description: "Black water, old wiring, movement where there should be none.",
    risk: 3,
    hours: 4,
    encounterChance: 0.38,
    enemies: ["stalker", "bloated_carrier"],
    loot: { scrap: [6, 10], parts: [4, 7], wire: [1, 3], ammo: [1, 3], relics: [0, 1] },
    itemPool: ["nail_bat", "relay_key"],
    itemChance: 0.22,
  },
  {
    id: "hospital_wing",
    name: "Hospital Wing",
    description: "Curtains stiff with dust, corridors still giving orders.",
    risk: 4,
    hours: 4,
    encounterChance: 0.42,
    enemies: ["screecher", "static_touched"],
    loot: { water: [1, 2], medicine: [2, 5], chemicals: [1, 2], parts: [2, 4], relics: [0, 1] },
    itemPool: ["riot_padding", "bandage_roll"],
    itemChance: 0.24,
  },
  {
    id: "radio_tower_perimeter",
    name: "Radio Tower Perimeter",
    description: "The fence hums even without power. Especially without power.",
    risk: 5,
    hours: 5,
    encounterChance: 0.5,
    enemies: ["static_touched", "relay_brute"],
    loot: { parts: [5, 9], wire: [2, 4], electronics: [1, 2], fuel: [2, 5], reputation: [2, 4], relics: [1, 2] },
    itemPool: ["tower_rifle", "static_lens"],
    itemChance: 0.26,
  },
  {
    id: "glass_orchard",
    name: "Glass Orchard",
    description: "An anomaly grove where frozen figures bloom from the road.",
    risk: 5,
    hours: 5,
    encounterChance: 0.48,
    enemies: ["stalker", "static_touched"],
    loot: { water: [1, 2], parts: [4, 6], electronics: [0, 1], morale: [1, 2], relics: [1, 3] },
    itemPool: ["signal_cloak", "odd_relic"],
    itemChance: 0.28,
  },
  {
    id: "hidden_bunker_entrance",
    name: "Hidden Bunker Entrance",
    description: "A concrete mouth under the city, still pretending not to exist.",
    risk: 6,
    hours: 5,
    encounterChance: 0.56,
    enemies: ["static_touched", "relay_brute"],
    loot: { scrap: [8, 12], parts: [6, 10], wire: [2, 4], electronics: [1, 2], reputation: [3, 5], relics: [2, 4] },
    itemPool: ["bunker_pass", "fire_axe"],
    itemChance: 0.32,
  },
];

export const ZONES_BY_ID = Object.fromEntries(ZONES.map((zone) => [zone.id, zone]));

export const FACTIONS = [
  {
    id: "signal_hunters",
    name: "Signal Hunters",
    description: "Patient scavengers of towers, frequencies, and truths.",
    bonuses: ["Directed radio sweeps build traces faster", "Hunter exchange opens signal-heavy deals", "Signal objectives pull deeper tech"],
    costs: ["Hotter signal work raises noise and raid attention"],
    effects: { radioDepth: 0.5, signalGain: 0.42, expeditionLootBonus: 0.05, traderDiscount: 0.04 },
    consequences: {
      tradeChannel: "hunter_exchange",
      objectiveBias: { signal: 0.16 },
      nightNoise: 0.25,
      raidBias: 0.04,
    },
  },
  {
    id: "iron_lantern",
    name: "Iron Lantern",
    description: "Militant keepers of lit ground and strict borders.",
    bonuses: ["Night defense and breach control improve immediately", "Lantern depot opens arms and medical stock", "Guards hit harder during pressure events"],
    costs: ["Anomaly tracing slows under their doctrine"],
    effects: { defense: 2, attack: 1, nightMitigation: 1.2 },
    consequences: {
      tradeChannel: "lantern_depot",
      raidMitigation: 0.14,
      breachMitigation: 0.1,
      anomalyPenalty: 0.2,
    },
  },
  {
    id: "ash_marauders",
    name: "Ash Marauders",
    description: "Mobile opportunists with a market ethic and bad manners.",
    bonuses: ["Hard pushes and sweep objectives return more salvage", "Broker channel favors ammo, caches, and ugly gear", "Close-quarters fighting gets meaner"],
    costs: ["Your shelter gets louder and raider attention climbs"],
    effects: { expeditionLootBonus: 0.15, attack: 1, salvageYieldBonus: 0.12, traderDiscount: 0.06 },
    consequences: {
      tradeChannel: "marauder_broker",
      objectiveBias: { salvage: 0.14, sweep: 0.12 },
      nightNoise: 0.35,
      raidBias: 0.08,
    },
  },
];

export const FACTIONS_BY_ID = Object.fromEntries(FACTIONS.map((faction) => [faction.id, faction]));

export const TRADER_CHANNELS = [
  {
    id: "open_market",
    name: "Open Market",
    description: "General traffic. Food, meds, loose wire, and whatever walks in without asking permission.",
    tag: "neutral",
  },
  {
    id: "hunter_exchange",
    name: "Hunter Exchange",
    description: "Signal Hunters trade in field tech, tower whispers, and relic-sensitive gear.",
    tag: "signal",
    requiresFaction: "signal_hunters",
  },
  {
    id: "lantern_depot",
    name: "Lantern Depot",
    description: "Iron Lantern stock runs military and defensive, priced like they know it.",
    tag: "defense",
    requiresFaction: "iron_lantern",
  },
  {
    id: "marauder_broker",
    name: "Marauder Broker",
    description: "Ash Marauders sell fast salvage, contraband rounds, and reckless routes.",
    tag: "salvage",
    requiresFaction: "ash_marauders",
  },
];

export const TRADER_CHANNELS_BY_ID = Object.fromEntries(TRADER_CHANNELS.map((channel) => [channel.id, channel]));

export const TRADER_OFFERS = [
  {
    id: "crate_meal",
    name: "Crate Meal",
    channels: ["open_market", "lantern_depot"],
    cost: { scrap: 14 },
    reward: { resources: { food: 3, water: 2, morale: 1 } },
    description: "Cans, jugs, and one good lie.",
  },
  {
    id: "field_meds",
    name: "Field Meds",
    channels: ["open_market", "lantern_depot"],
    cost: { scrap: 12, cloth: 1 },
    reward: { resources: { medicine: 2, chemicals: 1 }, grantItems: { bandage_roll: 1 } },
    description: "Bandages, pills, and no questions.",
  },
  {
    id: "wire_spool",
    name: "Wire Spool",
    channels: ["open_market", "hunter_exchange"],
    cost: { scrap: 10, parts: 1 },
    reward: { resources: { wire: 4, electronics: 1 } },
    description: "Insulated spool and one board still worth opening.",
  },
  {
    id: "tower_whisper",
    name: "Tower Whisper",
    channels: ["hunter_exchange"],
    cost: { fuel: 2, wire: 1, parts: 2 },
    reward: { resources: { reputation: 2 }, radioProgress: 1, radioTrace: { tower_grid: 1 } },
    description: "Directions spoken like a confession.",
  },
  {
    id: "loose_rounds",
    name: "Loose Rounds",
    channels: ["open_market", "marauder_broker"],
    cost: { scrap: 10, chemicals: 1, parts: 1 },
    reward: { resources: { ammo: 5 } },
    description: "Sorted by caliber, mostly.",
  },
  {
    id: "armor_bundle",
    name: "Armor Bundle",
    channels: ["lantern_depot"],
    cost: { scrap: 20, cloth: 2, parts: 4 },
    reward: { grantItems: { patchwork_vest: 1 } },
    description: "Cloth, leather, plates, and a lot of thread.",
  },
  {
    id: "rifle_cache",
    name: "Rifle Cache",
    channels: ["lantern_depot", "marauder_broker"],
    cost: { scrap: 24, ammo: 2, reputation: 2 },
    reward: { grantItems: { tower_rifle: 1 } },
    description: "Something long, cleaned, and hidden on purpose.",
  },
  {
    id: "relic_trade",
    name: "Relic Trade",
    channels: ["hunter_exchange"],
    cost: { relics: 1, scrap: 8 },
    reward: { resources: { fuel: 3, parts: 4, reputation: 1 } },
    description: "The lantern folk collect stranger things than you do.",
  },
  {
    id: "static_cloth",
    name: "Static Cloth",
    channels: ["hunter_exchange"],
    cost: { relics: 2, reputation: 2 },
    reward: { grantItems: { signal_cloak: 1 } },
    description: "Conductive fabric for people with bad priorities.",
  },
  {
    id: "breach_kit",
    name: "Breach Kit",
    channels: ["marauder_broker"],
    cost: { scrap: 18, parts: 3, fuel: 1 },
    reward: { resources: { ammo: 3, parts: 2 }, grantItems: { road_flare: 1 } },
    description: "Fast-entry tools and enough fire to leave fast too.",
  },
];

export const SCAVENGE_SOURCES = [
  {
    id: "rubble",
    label: "Search rubble",
    short: "RU",
    description: "Broken masonry, splintered frames, wet cloth, open pockets.",
    detail: "Balanced salvage for scrap, cloth, and loose finds. Good for starting runs, worse than a real wood or food lane once the shelter is standing.",
    focus: ["Scrap", "Cloth", "Drinkable Water"],
    tags: ["1h", "rising noise", "street debris"],
    hours: 1,
    threat: 0.42,
    noise: 0.52,
    scrapMod: { min: 0, max: 0 },
    directResources: {
      wood: [0, 1],
    },
    guaranteed: ["common"],
    rolls: [
      { rarity: "uncommon", chance: 0.74 },
      { rarity: "rare", chance: 0.16, rareBonus: 1 },
      { rarity: "epic", chance: 0.06, rareBonus: 0.45, requires: { searches: 10 } },
      { rarity: "legendary", chance: 0.025, rareBonus: 0.2, requires: { searches: 18 } },
      { rarity: "anomalous", chance: 0.018, rareBonus: 0.16, requires: { radioProgress: 4 } },
      { rarity: "mythic", chance: 0.012, rareBonus: 0.08, requires: { flags: ["worldReveal"] } },
    ],
    bonusChance: 0.58,
    rarityBias: { uncommon: 0.02, rare: 0.03 },
    logLabel: "the rubble",
    eventChance: 0.42,
  },
  {
    id: "tree_line",
    label: "Chop tree line",
    short: "TR",
    description: "Dead branches, fence timber, split trunks, and anything the shelter can burn or brace with.",
    detail: "Best early wood lane. It is slower than ripping pockets, but it turns daylight into walls, fire, and repairs.",
    focus: ["Wood", "Cloth", "Fuel"],
    tags: ["1h", "low noise", "wood lane"],
    hours: 1,
    threat: 0.22,
    noise: 0.24,
    scrapMod: { min: -2, max: -1 },
    directResources: {
      wood: [2, 3],
      cloth: [0, 1],
    },
    guaranteed: ["common"],
    rolls: [
      { rarity: "uncommon", chance: 0.44 },
      { rarity: "rare", chance: 0.1, rareBonus: 0.6 },
      { rarity: "epic", chance: 0.04, rareBonus: 0.2, requires: { upgrades: ["salvage_hatchet"] } },
    ],
    bonusChance: 0.34,
    rarityBias: { uncommon: 0.03 },
    requires: { searches: 4 },
    logLabel: "the tree line",
    eventChance: 0.24,
  },
  {
    id: "vehicle_shells",
    label: "Strip vehicle shells",
    short: "VH",
    description: "Dash metal, fuel lines, batteries, and glovebox lies.",
    detail: "Better for parts, wire, and fuel. Slightly louder than rubble and worth it.",
    focus: ["Parts", "Fuel", "Wire"],
    tags: ["1h", "medium noise", "engine blocks"],
    hours: 1,
    threat: 0.48,
    noise: 0.72,
    scrapMod: { min: 0, max: 1 },
    directResources: {
      parts: [1, 2],
      fuel: [0, 1],
    },
    guaranteed: ["common", "uncommon"],
    rolls: [
      { rarity: "rare", chance: 0.24, rareBonus: 1.1 },
      { rarity: "epic", chance: 0.1, rareBonus: 0.5, requires: { upgrades: ["crafting_bench"] } },
      { rarity: "legendary", chance: 0.045, rareBonus: 0.24, requires: { upgrades: ["watch_post"] } },
      { rarity: "anomalous", chance: 0.014, rareBonus: 0.1, requires: { radioProgress: 4 } },
    ],
    bonusChance: 0.66,
    rarityBias: { rare: 0.04, epic: 0.03 },
    requires: { searches: 4 },
    logLabel: "the vehicle shells",
    eventChance: 0.46,
  },
  {
    id: "dead_pantries",
    label: "Check dead pantries",
    short: "PN",
    description: "Cupboards, kitchen sinks, old shelves, and sealed luck.",
    detail: "Reliable food and water lane. Low yield in scrap, high value when hunger starts talking.",
    focus: ["Food", "Drinkable Water", "Medicine"],
    tags: ["1h", "quiet", "food lane"],
    hours: 1,
    threat: 0.28,
    noise: 0.26,
    scrapMod: { min: -1, max: 0 },
    directResources: {
      food: [1, 2],
      water: [1, 1],
    },
    guaranteed: ["common", "uncommon"],
    rolls: [
      { rarity: "rare", chance: 0.18, rareBonus: 0.9 },
      { rarity: "epic", chance: 0.08, rareBonus: 0.36, requires: { upgrades: ["food_crate"] } },
      { rarity: "legendary", chance: 0.022, rareBonus: 0.14, requires: { upgrades: ["smokehouse"] } },
    ],
    bonusChance: 0.54,
    rarityBias: { uncommon: 0.05, rare: 0.02 },
    requires: { upgrades: ["food_search"] },
    logLabel: "the dead pantries",
    eventChance: 0.36,
  },
  {
    id: "clinic_drawers",
    label: "Sweep clinic drawers",
    short: "CL",
    description: "Cracked cabinets, labelled trays, and pills no one came back for.",
    detail: "Medicine lane. Slower to open up, but it starts paying in clean painkillers and better tools.",
    focus: ["Medicine", "Chemicals", "Cloth"],
    tags: ["1h", "medium noise", "medical lane"],
    hours: 1,
    threat: 0.38,
    noise: 0.58,
    scrapMod: { min: -1, max: 0 },
    directResources: {
      medicine: [1, 1],
      cloth: [0, 1],
    },
    guaranteed: ["common", "uncommon"],
    rolls: [
      { rarity: "rare", chance: 0.3, rareBonus: 1.15 },
      { rarity: "epic", chance: 0.12, rareBonus: 0.5, requires: { upgrades: ["crafting_bench"] } },
      { rarity: "legendary", chance: 0.035, rareBonus: 0.18, requires: { upgrades: ["smokehouse"] } },
    ],
    bonusChance: 0.6,
    rarityBias: { rare: 0.05, epic: 0.03 },
    requires: { upgrades: ["first_aid_rag"] },
    logLabel: "the clinic drawers",
    eventChance: 0.44,
  },
  {
    id: "signal_wrecks",
    label: "Trace signal wrecks",
    short: "SG",
    description: "Tower scrap, relay boxes, antenna guts, and static-burned hardware.",
    detail: "Electronics lane. Stronger upper rarity access once the radio is online.",
    focus: ["Wire", "Electronics", "Relics"],
    tags: ["2h", "high noise", "signal lane"],
    hours: 2,
    threat: 0.62,
    noise: 1.18,
    scrapMod: { min: -1, max: 0 },
    directResources: {
      wire: [1, 2],
      electronics: [1, 1],
    },
    guaranteed: ["uncommon"],
    rolls: [
      { rarity: "rare", chance: 0.34, rareBonus: 1.2 },
      { rarity: "epic", chance: 0.18, rareBonus: 0.62, requires: { radioProgress: 1 } },
      { rarity: "legendary", chance: 0.085, rareBonus: 0.34, requires: { radioProgress: 2 } },
      { rarity: "anomalous", chance: 0.05, rareBonus: 0.24, requires: { radioProgress: 4 } },
      { rarity: "mythic", chance: 0.018, rareBonus: 0.12, requires: { flags: ["worldReveal"] } },
    ],
    bonusChance: 0.72,
    rarityBias: { epic: 0.05, legendary: 0.04, anomalous: 0.03 },
    requires: { upgrades: ["radio_rig"] },
    logLabel: "the signal wrecks",
    eventChance: 0.54,
  },
  {
    id: "sealed_caches",
    label: "Crack sealed caches",
    short: "SC",
    description: "Locked service cases, ammo tins, and someone else's emergency plan.",
    detail: "Late mid-game cache lane. Costs more threat and needs a pry bar, but pays with gear and upper-tier hardware.",
    focus: ["Ammo", "Parts", "Gear"],
    tags: ["2h", "high noise", "sealed stock"],
    hours: 2,
    threat: 0.72,
    noise: 1.34,
    scrapMod: { min: 0, max: 1 },
    directResources: {
      parts: [1, 2],
      ammo: [1, 2],
    },
    guaranteed: ["uncommon"],
    rolls: [
      { rarity: "rare", chance: 0.36, rareBonus: 1.2 },
      { rarity: "epic", chance: 0.2, rareBonus: 0.65, requires: { upgrades: ["crafting_bench"] } },
      { rarity: "legendary", chance: 0.12, rareBonus: 0.42, requires: { upgrades: ["watch_post"] } },
      { rarity: "anomalous", chance: 0.038, rareBonus: 0.2, requires: { secretProgress: 1 } },
      { rarity: "mythic", chance: 0.02, rareBonus: 0.12, requires: { flags: ["worldReveal"] } },
    ],
    bonusChance: 0.7,
    rarityBias: { rare: 0.03, epic: 0.06, legendary: 0.05 },
    requires: { upgrades: ["watch_post", "crafting_bench"], items: ["pry_bar"] },
    logLabel: "the sealed caches",
    eventChance: 0.58,
  },
];

export const SCAVENGE_SOURCES_BY_ID = Object.fromEntries(SCAVENGE_SOURCES.map((source) => [source.id, source]));

export const EXPEDITION_APPROACHES = [
  {
    id: "cautious",
    label: "Cautious",
    short: "quiet route",
    description: "Move slow, skip bad angles, and bring enough to wait things out.",
    cost: { food: 1, water: 1 },
    hours: 1,
    encounterDelta: -0.18,
    lootBonus: -0.1,
    threat: 0.08,
    noise: 0.12,
    travelEventChance: 0.28,
  },
  {
    id: "standard",
    label: "Standard",
    short: "balanced route",
    description: "The middle path. Not elegant. Usually survivable.",
    cost: {},
    hours: 0,
    encounterDelta: 0,
    lootBonus: 0,
    threat: 0.34,
    noise: 0.48,
    travelEventChance: 0.38,
  },
  {
    id: "forced",
    label: "Forced",
    short: "fast and loud",
    description: "Push hard, break locks, and accept that everything hears you.",
    cost: { water: 1, fuel: 1, ammo: 1 },
    hours: -1,
    encounterDelta: 0.16,
    lootBonus: 0.12,
    threat: 0.78,
    noise: 1.18,
    travelEventChance: 0.58,
  },
];

export const EXPEDITION_APPROACHES_BY_ID = Object.fromEntries(EXPEDITION_APPROACHES.map((approach) => [approach.id, approach]));

export const EXPEDITION_OBJECTIVES = [
  {
    id: "salvage",
    label: "Salvage",
    short: "metal + parts",
    description: "Strip weight, pry hardware, and come back heavier than you left.",
    resourceBias: { scrap: 0.3, parts: 0.18, wire: 0.1, fuel: 0.08 },
    itemChanceBonus: 0.02,
    encounterDelta: 0.06,
    hours: 0,
    threat: 0.14,
    noise: 0.18,
    tags: ["yield", "parts", "louder"],
  },
  {
    id: "provisions",
    label: "Provisions",
    short: "food + water",
    description: "Aim for cupboards, clean water, and anything that keeps the room fed.",
    resourceBias: { food: 0.36, water: 0.26, cloth: 0.1, medicine: 0.06 },
    itemChanceBonus: 0.02,
    encounterDelta: -0.08,
    hours: 0,
    threat: -0.08,
    noise: -0.12,
    tags: ["safer", "food", "water"],
  },
  {
    id: "medicine",
    label: "Medicine",
    short: "meds + chems",
    description: "Push into cabinets, triage rooms, and cold storage looking for clean help.",
    resourceBias: { medicine: 0.46, chemicals: 0.28, water: 0.08, cloth: 0.08 },
    itemChanceBonus: 0.05,
    encounterDelta: 0.05,
    hours: 1,
    threat: 0.1,
    noise: 0.06,
    tags: ["slow", "medical", "clean"],
  },
  {
    id: "signal",
    label: "Signal",
    short: "tech + clues",
    description: "Chase relay boxes, tower residue, and strange hardware with a pulse still in it.",
    resourceBias: { wire: 0.16, electronics: 0.28, reputation: 0.16, relics: 0.1, parts: 0.1 },
    itemChanceBonus: 0.08,
    encounterDelta: 0.08,
    hours: 1,
    threat: 0.18,
    noise: 0.2,
    traceGain: { tower_grid: 1.2, anomaly_trace: 0.7 },
    tags: ["tech", "clues", "hot"],
  },
  {
    id: "sweep",
    label: "Sweep",
    short: "fight + caches",
    description: "Push hard, clear movement, and accept that the route may turn into a brawl.",
    resourceBias: { ammo: 0.24, parts: 0.18, scrap: 0.12, relics: 0.08 },
    itemChanceBonus: 0.1,
    encounterDelta: 0.16,
    hours: -1,
    threat: 0.26,
    noise: 0.3,
    combatBonus: 1,
    tags: ["combat", "fast", "cache"],
  },
];

export const EXPEDITION_OBJECTIVES_BY_ID = Object.fromEntries(EXPEDITION_OBJECTIVES.map((objective) => [objective.id, objective]));

export const EXPEDITION_ROUTE_EVENTS = [
  {
    id: "quiet_cutthrough",
    label: "Quiet cut-through",
    text: "You find a narrow service cut-through and shave a full block off the route without waking anything worth naming.",
    approaches: ["cautious"],
    weight: 3,
    encounterDelta: -0.12,
    timeDelta: -1,
    threatDelta: -0.08,
  },
  {
    id: "locker_rattle",
    label: "Rattled lockers",
    text: "A bank of service lockers gives way. The noise buys you more salvage and more attention at the same time.",
    objectives: ["salvage", "sweep"],
    weight: 3,
    resources: { scrap: 3, parts: 2 },
    encounterDelta: 0.08,
    noiseDelta: 0.18,
  },
  {
    id: "cold_pantry",
    label: "Cold pantry",
    text: "A sealed pantry room still holds clean tins and bottled water if you move fast and carry it all.",
    objectives: ["provisions"],
    weight: 3,
    resources: { food: 2, water: 2 },
    lootBonus: 0.06,
  },
  {
    id: "surgical_cart",
    label: "Surgical cart",
    text: "An overturned treatment cart gives up bandages and bitter pills after you drag it free.",
    objectives: ["medicine"],
    zones: ["hospital_wing", "burned_apartments"],
    weight: 3,
    resources: { medicine: 1, chemicals: 1 },
    condition: 2,
  },
  {
    id: "signal_ping",
    label: "Signal ping",
    text: "A live relay ping answers your sweep. It does not last long, but it gives the board another clean angle.",
    objectives: ["signal"],
    weight: 4,
    radioTrace: { tower_grid: 0.8, anomaly_trace: 0.35 },
    resources: { reputation: 1 },
  },
  {
    id: "maintenance_marker",
    label: "Maintenance marker",
    text: "Old route paint points deeper into the city underworks. The mark matters more than the scrap around it.",
    objectives: ["signal", "medicine"],
    weight: 2,
    radioTrace: { sublevel_echo: 0.8 },
    secretProgress: 1,
  },
  {
    id: "flood_detour",
    label: "Flood detour",
    text: "The route collapses into flood water and bad footing. You make it through slower and meaner than planned.",
    zones: ["flooded_tunnel", "hospital_wing"],
    weight: 2,
    timeDelta: 1,
    encounterDelta: 0.08,
    condition: -4,
  },
  {
    id: "watcher_nest",
    label: "Watcher nest",
    text: "A half-cleared nest forces a fast violent push. You get the route, but the route gets a piece of you too.",
    objectives: ["sweep"],
    approaches: ["forced", "standard"],
    weight: 3,
    lootBonus: 0.08,
    encounterDelta: 0.1,
    stress: 1,
  },
  {
    id: "sealed_case",
    label: "Sealed case",
    text: "A reinforced transit case opens under leverage and patience, paying out better gear than the lane promised.",
    items: ["pry_bar", "hand_drill"],
    weight: 2,
    resources: { parts: 2, ammo: 1 },
    lootBonus: 0.1,
  },
  {
    id: "dead_drop",
    label: "Dead drop",
    text: "Someone marked a supply dead drop and never came back for it. Their loss is route discipline for another day.",
    day: 4,
    weight: 2,
    resources: { food: 1, water: 1, ammo: 1, parts: 1 },
    morale: 1,
  },
];

export const EXPEDITION_ROUTE_EVENTS_BY_ID = Object.fromEntries(EXPEDITION_ROUTE_EVENTS.map((event) => [event.id, event]));

export const RADIO_INVESTIGATIONS = [
  {
    id: "civic_band",
    label: "Civic Band",
    short: "archive traffic",
    description: "Sweep old emergency channels, public dispatch, and evacuation spillover.",
    traceLabel: "Archive trace",
    milestones: [
      {
        id: "civic_dispatch",
        at: 1,
        text: "Archive traffic resolves into a calm evacuation countdown and a hospital wing repeating under it.",
        effects: { radioProgress: 1, resources: { reputation: 1 }, unlockZones: ["hospital_wing"] },
      },
      {
        id: "civic_market",
        at: 3,
        text: "Price codes and lantern marks bleed into the civic band, but the real value is the route chatter hiding under them.",
        effects: { radioProgress: 1, resources: { reputation: 1, parts: 1 } },
      },
      {
        id: "civic_rumor",
        at: 5,
        text: "The old city band knows route names the living are still using. Someone kept listening after everyone else stopped.",
        effects: { radioProgress: 1, resources: { reputation: 2 } },
      },
    ],
  },
  {
    id: "tower_grid",
    label: "Tower Grid",
    short: "tower relays",
    description: "Triangulate tower relay bursts and the channels built to carry them.",
    traceLabel: "Tower trace",
    milestones: [
      {
        id: "tower_perimeter",
        at: 1,
        text: "A clipped tower handoff maps the perimeter and proves the fence still talks when it should be dead.",
        effects: { radioProgress: 1, unlockZones: ["radio_tower_perimeter"] },
      },
      {
        id: "tower_cells",
        at: 3,
        text: "The tower grid starts naming its own maintenance cells. There are more hands on the signal than you thought.",
        effects: { radioProgress: 1, resources: { electronics: 1, reputation: 1 }, secretProgress: 1 },
      },
      {
        id: "tower_hunters",
        at: 5,
        text: "Signal Hunters stop sounding like rumor and start sounding like a coordinated network sitting right on top of the grid.",
        effects: { radioProgress: 1, resources: { reputation: 3 } },
      },
    ],
  },
  {
    id: "sublevel_echo",
    label: "Sublevel Echo",
    short: "maintenance routes",
    description: "Track maintenance routes, drowned service lines, and concrete that still breathes on the band.",
    traceLabel: "Sublevel trace",
    milestones: [
      {
        id: "sublevel_tunnel",
        at: 1,
        text: "Flood-control calls line up into a maintenance route beneath the streets.",
        effects: { radioProgress: 1, unlockZones: ["flooded_tunnel"] },
      },
      {
        id: "sublevel_breath",
        at: 3,
        text: "A sealed air-handling loop opens for a second, then cuts out before you can answer it.",
        effects: { secretProgress: 1 },
      },
      {
        id: "sublevel_bunker",
        at: 5,
        text: "The sublevel pattern repeats around a hardened door schedule. There is a bunker route under the city after all.",
        effects: { radioProgress: 1, secretProgress: 1, setFlags: { bunkerRouteKnown: true }, unlockZones: ["hidden_bunker_entrance"] },
      },
    ],
  },
  {
    id: "anomaly_trace",
    label: "Anomaly Trace",
    short: "impossible carrier",
    description: "Push past archive noise and track the places where static behaves like a living system.",
    traceLabel: "Anomaly trace",
    milestones: [
      {
        id: "anomaly_orchard",
        at: 1,
        text: "A child's voice keeps naming a place called the Glass Orchard like it expects you to know the way.",
        effects: { secretProgress: 1, unlockZones: ["glass_orchard"] },
      },
      {
        id: "anomaly_relic",
        at: 3,
        text: "The trace stabilizes long enough to pull a relic-bearing carrier out of the hiss.",
        effects: { radioProgress: 1, resources: { relics: 1 } },
      },
      {
        id: "anomaly_dead_static",
        at: 5,
        text: "The anomaly layer stops acting like weather and starts acting like infrastructure. The static was built.",
        effects: { radioProgress: 1, secretProgress: 1 },
      },
    ],
  },
];

export const RADIO_INVESTIGATIONS_BY_ID = Object.fromEntries(RADIO_INVESTIGATIONS.map((investigation) => [investigation.id, investigation]));

export const SEARCH_LOOT_TABLE = [
  {
    id: "loot_scrap",
    type: "resource",
    key: "scrap",
    amount: [1, 3],
    rarity: "common",
    weight: 28,
  },
  {
    id: "loot_cloth",
    type: "resource",
    key: "cloth",
    amount: [1, 2],
    rarity: "common",
    weight: 18,
  },
  {
    id: "loot_water",
    type: "resource",
    key: "water",
    amount: [1, 1],
    rarity: "common",
    weight: 10,
  },
  {
    id: "loot_food",
    type: "resource",
    key: "food",
    amount: [1, 2],
    rarity: "uncommon",
    weight: 12,
    sources: ["dead_pantries"],
  },
  {
    id: "loot_parts",
    type: "resource",
    key: "parts",
    amount: [1, 2],
    rarity: "uncommon",
    weight: 12,
    sources: ["vehicle_shells", "sealed_caches"],
  },
  {
    id: "loot_wire",
    type: "resource",
    key: "wire",
    amount: [1, 2],
    rarity: "uncommon",
    weight: 9,
    sources: ["rubble", "vehicle_shells", "signal_wrecks"],
  },
  {
    id: "loot_fuel",
    type: "resource",
    key: "fuel",
    amount: [1, 1],
    rarity: "uncommon",
    weight: 8,
    sources: ["vehicle_shells", "sealed_caches"],
  },
  {
    id: "loot_beans",
    type: "item",
    key: "canned_beans",
    amount: [1, 1],
    rarity: "uncommon",
    weight: 6,
    sources: ["dead_pantries"],
  },
  {
    id: "loot_cloth_bundle",
    type: "resource",
    key: "cloth",
    amount: [2, 3],
    rarity: "uncommon",
    weight: 5,
    requires: { searches: 5 },
    sources: ["rubble", "dead_pantries", "clinic_drawers"],
  },
  {
    id: "loot_medicine",
    type: "resource",
    key: "medicine",
    amount: [1, 1],
    rarity: "rare",
    weight: 5,
    sources: ["dead_pantries", "clinic_drawers"],
  },
  {
    id: "loot_ammo",
    type: "resource",
    key: "ammo",
    amount: [1, 2],
    rarity: "rare",
    weight: 4,
    sources: ["sealed_caches"],
  },
  {
    id: "loot_electronics",
    type: "resource",
    key: "electronics",
    amount: [1, 1],
    rarity: "rare",
    weight: 4,
    sources: ["signal_wrecks", "sealed_caches"],
  },
  {
    id: "loot_chemicals",
    type: "resource",
    key: "chemicals",
    amount: [1, 1],
    rarity: "rare",
    weight: 4,
    sources: ["clinic_drawers", "vehicle_shells"],
  },
  {
    id: "loot_sharp_metal",
    type: "item",
    key: "sharp_metal",
    amount: [1, 1],
    rarity: "rare",
    weight: 3,
    sources: ["rubble", "vehicle_shells"],
  },
  {
    id: "loot_bandage_roll",
    type: "item",
    key: "bandage_roll",
    amount: [1, 1],
    rarity: "rare",
    weight: 2,
    requires: { searches: 8 },
    sources: ["clinic_drawers", "dead_pantries"],
  },
  {
    id: "loot_road_flare",
    type: "item",
    key: "road_flare",
    amount: [1, 1],
    rarity: "rare",
    weight: 3,
    requires: { searches: 6 },
    sources: ["vehicle_shells"],
  },
  {
    id: "loot_field_filter",
    type: "item",
    key: "field_filter",
    amount: [1, 1],
    rarity: "rare",
    weight: 3,
    requires: { upgrades: ["food_search"] },
    sources: ["dead_pantries", "clinic_drawers"],
  },
  {
    id: "loot_fuel_cell",
    type: "item",
    key: "fuel_cell",
    amount: [1, 1],
    rarity: "epic",
    weight: 4,
    requires: { searches: 10 },
    sources: ["vehicle_shells", "sealed_caches"],
  },
  {
    id: "loot_clinic_case",
    type: "item",
    key: "clinic_case",
    amount: [1, 1],
    rarity: "epic",
    weight: 3,
    requires: { upgrades: ["first_aid_rag", "crafting_bench"] },
    sources: ["clinic_drawers"],
  },
  {
    id: "loot_electronics_cache",
    type: "resource",
    key: "electronics",
    amount: [2, 3],
    rarity: "epic",
    weight: 3,
    requires: { upgrades: ["crafting_bench"] },
    sources: ["signal_wrecks", "sealed_caches"],
  },
  {
    id: "loot_pry_bar",
    type: "item",
    key: "pry_bar",
    amount: [1, 1],
    rarity: "epic",
    weight: 3,
    requires: { searches: 12, upgrades: ["crafting_bench"] },
    sources: ["rubble", "vehicle_shells", "sealed_caches"],
  },
  {
    id: "loot_coil_spike",
    type: "item",
    key: "coil_spike",
    amount: [1, 1],
    rarity: "epic",
    weight: 2,
    requires: { radioProgress: 1, upgrades: ["crafting_bench"] },
    sources: ["signal_wrecks"],
  },
  {
    id: "loot_patchwork_vest",
    type: "item",
    key: "patchwork_vest",
    amount: [1, 1],
    rarity: "legendary",
    weight: 2,
    requires: { searches: 16, upgrades: ["armor_hooks"] },
    sources: ["sealed_caches"],
  },
  {
    id: "loot_transit_pistol",
    type: "item",
    key: "transit_pistol",
    amount: [1, 1],
    rarity: "legendary",
    weight: 2,
    requires: { searches: 16, upgrades: ["weapon_rack"] },
    sources: ["sealed_caches"],
  },
  {
    id: "loot_tower_battery",
    type: "item",
    key: "tower_battery",
    amount: [1, 1],
    rarity: "legendary",
    weight: 2,
    requires: { radioProgress: 2, upgrades: ["radio_rig"] },
    sources: ["signal_wrecks"],
  },
  {
    id: "loot_relics",
    type: "resource",
    key: "relics",
    amount: [1, 1],
    rarity: "legendary",
    weight: 3,
    requires: { radioProgress: 4 },
    sources: ["signal_wrecks"],
  },
  {
    id: "loot_odd_relic",
    type: "item",
    key: "odd_relic",
    amount: [1, 1],
    rarity: "anomalous",
    weight: 2,
    requires: { secretProgress: 2 },
    sources: ["signal_wrecks"],
  },
  {
    id: "loot_static_lens",
    type: "item",
    key: "static_lens",
    amount: [1, 1],
    rarity: "mythic",
    weight: 1,
    requires: { flags: ["worldReveal"] },
    sources: ["signal_wrecks"],
  },
];
