export const UPGRADES = [
  {
    id: "backpack",
    name: "Backpack",
    description: "Stitch scavenged cloth and straps into something worth carrying.",
    verb: "Rig",
    cost: { scrap: 8, cloth: 3 },
    requires: { searches: 3 },
    effects: { searchScrapMin: 1, searchScrapMax: 1, searchBonusRolls: 1 },
  },
  {
    id: "rusty_knife",
    name: "Rusty Knife",
    description: "Wrap a sharp shard, bind the handle, and call it honest work.",
    verb: "Bind",
    cost: { scrap: 6, parts: 3, cloth: 1 },
    materials: { sharp_metal: 1 },
    requires: { searches: 4 },
    effects: {
      attack: 1,
      grantItems: { rusty_knife: 1 },
      unlockSections: ["inventory"],
    },
  },
  {
    id: "shelter_stash",
    name: "Shelter Stash",
    description: "A corner that counts as ownership.",
    verb: "Secure",
    cost: { scrap: 14, wood: 4, cloth: 2 },
    requires: { searches: 4 },
    effects: {
      unlockSections: ["shelter"],
      discoverResources: ["food"],
      defense: 1,
    },
  },
  {
    id: "campfire",
    name: "Campfire",
    description: "A controlled glow beats a cold death.",
    verb: "Assemble",
    cost: { scrap: 18, wood: 3, fuel: 2, cloth: 1 },
    requires: { upgrades: ["shelter_stash"], burnUses: 1 },
    effects: {
      burnCondition: 5,
      defense: 1,
      discoverResources: ["fuel"],
      unlockSections: ["shelter"],
    },
  },
  {
    id: "basic_barricade",
    name: "Basic Barricade",
    description: "It will not stop everything. It does not need to.",
    verb: "Brace",
    cost: { scrap: 24, wood: 5, parts: 4, wire: 2 },
    requires: { upgrades: ["shelter_stash"] },
    effects: { defense: 2, nightMitigation: 0.35, unlockSections: ["shelter"] },
  },
  {
    id: "first_aid_rag",
    name: "First Aid Rag",
    description: "A filthy medical miracle.",
    cost: { cloth: 2, medicine: 1 },
    requires: { searches: 5 },
    effects: {
      grantItems: { first_aid_rag: 1 },
      discoverResources: ["medicine"],
    },
  },
  {
    id: "food_search",
    name: "Simple Food Search",
    description: "Separate hunger from useful scrap before both kill you.",
    cost: { scrap: 14, wood: 2, water: 1 },
    requires: { upgrades: ["shelter_stash"] },
    effects: {
      searchFoodChance: 0.08,
      searchBonusRolls: 1,
    },
  },
  {
    id: "small_scavenge",
    name: "Small Scavenging Runs",
    description: "A cautious loop beyond line of sight.",
    cost: { scrap: 28, food: 2, water: 2 },
    requires: { upgrades: ["backpack", "rusty_knife"] },
    effects: {
      unlockSections: ["map"],
      unlockZones: ["ruined_street"],
      expeditionLootBonus: 0.03,
    },
  },
  {
    id: "food_crate",
    name: "Food Storage",
    description: "Enough order to keep hunger from winning by accounting.",
    cost: { scrap: 30, wood: 4, parts: 5, cloth: 2 },
    requires: { upgrades: ["food_search"] },
    effects: {
      forageYieldBonus: 0.14,
      discoverResources: ["food"],
    },
  },
  {
    id: "crafting_bench",
    name: "Crafting Bench",
    description: "The first place built for making instead of hiding.",
    cost: { scrap: 34, wood: 4, parts: 8, wire: 2 },
    requires: { upgrades: ["small_scavenge"] },
    effects: {
      searchPartChance: 0.06,
      rareLootBonus: 0.06,
      unlockSections: ["inventory"],
    },
  },
  {
    id: "pry_bar_tool",
    name: "Pry Bar",
    description: "Leverage wins fights with crates, doors, and sealed salvage before they start.",
    verb: "Forge",
    cost: { scrap: 14, wood: 1, parts: 4, cloth: 1 },
    materials: { sharp_metal: 1 },
    requires: { upgrades: ["crafting_bench"] },
    effects: {
      grantItems: { pry_bar: 1 },
      searchPartChance: 0.08,
      salvageYieldBonus: 0.06,
      unlockSections: ["inventory"],
    },
  },
  {
    id: "salvage_hatchet",
    name: "Salvage Hatchet",
    description: "A compact splitter for timber, weak boards, and ugly shelter work.",
    verb: "Forge",
    cost: { scrap: 16, wood: 3, parts: 3, cloth: 1 },
    materials: { sharp_metal: 1 },
    requires: { upgrades: ["crafting_bench"] },
    effects: {
      grantItems: { salvage_hatchet: 1 },
      forageYieldBonus: 0.08,
      nightMitigation: 0.15,
      unlockSections: ["inventory"],
    },
  },
  {
    id: "weapon_rack",
    name: "Weapon Slot",
    description: "A proper place for a proper answer.",
    cost: { scrap: 34, wood: 2, parts: 6, wire: 1 },
    requires: { upgrades: ["crafting_bench"] },
    effects: {
      weaponSlot: true,
      unlockSections: ["inventory"],
      attack: 1,
    },
  },
  {
    id: "armor_hooks",
    name: "Armor Slot",
    description: "A wall of hooks for whatever passes as protection now.",
    cost: { scrap: 34, wood: 2, parts: 6, cloth: 2 },
    requires: { upgrades: ["crafting_bench"] },
    effects: {
      armorSlot: true,
      unlockSections: ["inventory"],
      defense: 1,
    },
  },
  {
    id: "watch_post",
    name: "Watch Post",
    description: "Higher eyes make the nights shorter.",
    cost: { scrap: 46, wood: 7, parts: 8, wire: 2 },
    requires: { upgrades: ["basic_barricade"] },
    effects: {
      defense: 3,
      survivorCap: 1,
      expeditionEncounterAdjust: -0.04,
      nightMitigation: 0.45,
    },
  },
  {
    id: "ammo_press",
    name: "Ammo Press",
    description: "No bullets appear on purpose by accident.",
    cost: { scrap: 40, wood: 2, parts: 10, chemicals: 3 },
    requires: { upgrades: ["crafting_bench"] },
    effects: {
      discoverResources: ["ammo"],
      rareLootBonus: 0.04,
    },
  },
  {
    id: "rain_collector",
    name: "Rain Collector",
    description: "A cleaner mouthful than the old pipes.",
    cost: { scrap: 28, wood: 4, parts: 5, cloth: 2, wire: 2 },
    requires: { upgrades: ["shelter_stash"] },
    effects: {
      conditionRegen: 0.01,
      passive: { water: 0.015 },
      forageYieldBonus: 0.08,
    },
  },
  {
    id: "radio_rig",
    name: "Radio",
    description: "The dead city still has a voice.",
    cost: { scrap: 32, parts: 10, wire: 5, electronics: 3, fuel: 2 },
    requires: { upgrades: ["watch_post"] },
    effects: {
      unlockSections: ["radio"],
      radioDepth: 0.35,
      discoverResources: ["reputation"],
    },
  },
  {
    id: "map_board",
    name: "Map",
    description: "A wall of routes, guesses, and exits that failed.",
    cost: { scrap: 32, wood: 3, parts: 5, cloth: 2 },
    requires: { upgrades: ["small_scavenge"] },
    effects: {
      unlockSections: ["map"],
      unlockZones: ["burned_apartments", "abandoned_gas_station"],
    },
  },
  {
    id: "survivor_cots",
    name: "Survivor Recruitment",
    description: "A second mattress is a public statement.",
    cost: { scrap: 36, wood: 6, food: 4, water: 3, cloth: 4 },
    requires: { upgrades: ["food_crate"] },
    effects: {
      unlockSections: ["survivors"],
      discoverResources: ["morale"],
      survivorCap: 2,
    },
  },
  {
    id: "smokehouse",
    name: "Smokehouse",
    description: "A shelter that smells like tomorrow.",
    cost: { scrap: 48, wood: 8, parts: 8, fuel: 4, cloth: 2 },
    requires: { upgrades: ["food_crate"] },
    effects: {
      forageYieldBonus: 0.22,
      conditionRegen: 0.01,
    },
  },
  {
    id: "trader_beacon",
    name: "Signal Beacon",
    description: "A disciplined tower mark that sharpens the shelter line instead of advertising a market.",
    cost: { scrap: 40, wood: 3, parts: 8, wire: 3, fuel: 4 },
    requires: { upgrades: ["radio_rig"] },
    effects: {
      signalGain: 0.18,
      nightMitigation: 0.35,
    },
  },
  {
    id: "scout_bike",
    name: "Scout Bike",
    description: "Fast enough to be reckless on purpose.",
    cost: { scrap: 52, parts: 14, fuel: 8, electronics: 2 },
    requires: { upgrades: ["map_board"] },
    effects: {
      unlockZones: ["flooded_tunnel", "hospital_wing"],
      expeditionLootBonus: 0.08,
      scoutBonus: 0.04,
    },
  },
  {
    id: "signal_decoder",
    name: "Signal Decoder",
    description: "Translates the hiss into intent.",
    cost: { scrap: 52, parts: 14, wire: 4, electronics: 4, relics: 2 },
    requires: { upgrades: ["radio_rig"], radioProgress: 2 },
    effects: {
      radioDepth: 0.75,
      signalGain: 0.12,
      secretProgress: 1,
    },
  },
  {
    id: "auto_scavenger",
    name: "Auto Scavenger",
    description: "A dumb rig that can still find bright metal.",
    cost: { scrap: 68, wood: 4, parts: 18, wire: 4, fuel: 6 },
    requires: { upgrades: ["survivor_cots", "watch_post"] },
    effects: {
      passive: {
        scrap: 0.02,
        parts: 0.008,
      },
      salvageYieldBonus: 0.08,
      scoutBonus: 0.04,
    },
  },
  {
    id: "faraday_mesh",
    name: "Faraday Mesh",
    description: "Wire the walls before the walls start listening back.",
    cost: { scrap: 64, parts: 18, wire: 8, electronics: 2, relics: 2 },
    requires: { upgrades: ["signal_decoder"] },
    effects: {
      defense: 4,
      nightMitigation: 0.85,
    },
  },
  {
    id: "relay_tap",
    name: "Relay Tap",
    description: "Steal power from a signal that never asked permission.",
    cost: { scrap: 66, parts: 20, wire: 7, electronics: 4, fuel: 8 },
    requires: { upgrades: ["trader_beacon"], radioProgress: 4 },
    effects: {
      radioDepth: 0.55,
      signalGain: 0.22,
      anomalyGain: 0.2,
    },
  },
  {
    id: "bunker_drill",
    name: "Bunker Drill",
    description: "Something under the city was not meant to open easily.",
    cost: { scrap: 78, parts: 22, wire: 6, fuel: 12, relics: 3 },
    requires: { upgrades: ["signal_decoder"], secretProgress: 2 },
    effects: {
      unlockZones: ["hidden_bunker_entrance"],
      secretProgress: 1,
    },
  },
];

export const UPGRADES_BY_ID = Object.fromEntries(UPGRADES.map((upgrade) => [upgrade.id, upgrade]));

export const ENEMIES = {
  walker: {
    id: "walker",
    name: "Walker",
    hp: 14,
    attack: [3, 5],
    reward: { scrap: 1 },
    description: "Slow, wet footsteps and no intention of stopping.",
    behavior: {
      defaultIntent: "grapple",
      intents: ["grapple", "lunge", "lunge"],
      gripChance: 0.35,
      gripPenalty: 0.18,
      aftermathThreat: 0.22,
      summary: "Likes to pin and drag the fight into a blunt mess.",
    },
    ascii: [
      "   .-.   ",
      "  (o o)  ",
      "  | O |  ",
      "  |   |  ",
      "  '~~~'  ",
    ],
  },
  screecher: {
    id: "screecher",
    name: "Screecher",
    hp: 18,
    attack: [4, 7],
    reward: { scrap: 1, ammo: 1 },
    description: "All throat, no restraint.",
    behavior: {
      defaultIntent: "shriek",
      intents: ["shriek", "lunge", "shriek"],
      shriekThreat: 0.45,
      shriekNoise: 0.6,
      retreatPenalty: 0.12,
      summary: "Builds pressure if you leave it alive or let it run.",
    },
    ascii: [
      "  .---.  ",
      " / x x \\ ",
      "|   ^   |",
      "|  ---  |",
      " \\\\___// ",
    ],
  },
  bloated_carrier: {
    id: "bloated_carrier",
    name: "Bloated Carrier",
    hp: 24,
    attack: [5, 8],
    reward: { fuel: 1, medicine: 1 },
    description: "Swollen with rot and useful things.",
    behavior: {
      defaultIntent: "rupture",
      intents: ["rupture", "lunge", "rupture"],
      deathBurst: { chemicals: 1, medicine: 1 },
      deathSplash: 3,
      summary: "Can burst open on death and splash anyone too close.",
    },
    ascii: [
      "  .---.  ",
      " ( ___ ) ",
      "| (___) |",
      "|  :::  |",
      " '-----' ",
    ],
  },
  stalker: {
    id: "stalker",
    name: "Stalker",
    hp: 22,
    attack: [6, 9],
    reward: { parts: 2 },
    description: "Quiet enough to feel unfair.",
    behavior: {
      defaultIntent: "ambush",
      intents: ["ambush", "lunge", "feint"],
      openerBonus: [2, 4],
      retreatPenalty: 0.2,
      summary: "Opens hard and punishes retreat if you lose the angle.",
    },
    ascii: [
      "  /\\_/\\\\ ",
      " ( o.o )",
      "  > ^ < ",
      " //   \\\\",
      "//     \\\\",
    ],
  },
  static_touched: {
    id: "static_touched",
    name: "Static-Touched",
    hp: 32,
    attack: [7, 11],
    reward: { relics: 1, parts: 2 },
    description: "Moves to a rhythm the city should have lost years ago.",
    behavior: {
      defaultIntent: "pulse",
      intents: ["pulse", "lunge", "pulse"],
      signalBurn: 0.35,
      moraleHit: 1,
      summary: "Builds static pressure and drains radio certainty mid-fight.",
    },
    ascii: [
      "  .:::.  ",
      " ( o o ) ",
      " /  ^  \\\\",
      "| '--' | ",
      " \\\\_=_// ",
    ],
  },
  relay_brute: {
    id: "relay_brute",
    name: "Relay Brute",
    hp: 40,
    attack: [9, 13],
    reward: { relics: 2, reputation: 1 },
    description: "Tower muscle wrapped in old transmitter mesh.",
    behavior: {
      defaultIntent: "crush",
      intents: ["crush", "lunge", "crush"],
      armor: 1,
      breachDamage: 1,
      summary: "Soaks weak hits and hits hard enough to damage shelter confidence.",
    },
    ascii: [
      " [#####] ",
      " (x x x) ",
      " /|===|\\\\",
      "/_|___|_\\\\",
      "  /   \\\\ ",
    ],
  },
};

export const ZONES = [
  {
    id: "ruined_street",
    name: "Ruined Street",
    description: "Crushed storefronts, dead traffic, loose copper in the walls.",
    risk: 1,
    hours: 2,
    encounterChance: 0.2,
    enemies: ["walker", "screecher"],
    loot: { scrap: [5, 9], wood: [2, 4], cloth: [1, 2], water: [0, 1], food: [0, 2], parts: [1, 2], fuel: [0, 1] },
    itemPool: ["pry_bar", "canned_beans"],
    itemChance: 0.16,
  },
  {
    id: "burned_apartments",
    name: "Burned Apartments",
    description: "Stacked smoke damage and private tragedies.",
    risk: 2,
    hours: 3,
    encounterChance: 0.28,
    enemies: ["walker", "stalker"],
    loot: { scrap: [7, 12], wood: [2, 5], cloth: [1, 3], water: [1, 2], food: [1, 3], parts: [2, 4], medicine: [0, 1] },
    itemPool: ["patchwork_vest", "bandage_roll"],
    itemChance: 0.2,
  },
  {
    id: "abandoned_gas_station",
    name: "Abandoned Gas Station",
    description: "The pumps are dry, but the tanks forgot that.",
    risk: 2,
    hours: 3,
    encounterChance: 0.3,
    enemies: ["walker", "bloated_carrier"],
    loot: { scrap: [4, 8], water: [0, 1], fuel: [2, 5], parts: [1, 3], chemicals: [0, 1] },
    itemPool: ["fuel_cell", "transit_pistol"],
    itemChance: 0.2,
  },
  {
    id: "flooded_tunnel",
    name: "Flooded Tunnel",
    description: "Black water, old wiring, movement where there should be none.",
    risk: 3,
    hours: 4,
    encounterChance: 0.38,
    enemies: ["stalker", "bloated_carrier"],
    loot: { scrap: [6, 10], parts: [4, 7], wire: [1, 3], ammo: [1, 3], relics: [0, 1] },
    itemPool: ["nail_bat", "relay_key"],
    itemChance: 0.22,
  },
  {
    id: "hospital_wing",
    name: "Hospital Wing",
    description: "Curtains stiff with dust, corridors still giving orders.",
    risk: 4,
    hours: 4,
    encounterChance: 0.42,
    enemies: ["screecher", "static_touched"],
    loot: { water: [1, 2], medicine: [2, 5], chemicals: [1, 2], parts: [2, 4], relics: [0, 1] },
    itemPool: ["riot_padding", "bandage_roll"],
    itemChance: 0.24,
  },
  {
    id: "radio_tower_perimeter",
    name: "Radio Tower Perimeter",
    description: "The fence hums even without power. Especially without power.",
    risk: 5,
    hours: 5,
    encounterChance: 0.5,
    enemies: ["static_touched", "relay_brute"],
    loot: { parts: [5, 9], wire: [2, 4], electronics: [1, 2], fuel: [2, 5], reputation: [2, 4], relics: [1, 2] },
    itemPool: ["tower_rifle", "static_lens"],
    itemChance: 0.26,
  },
  {
    id: "glass_orchard",
    name: "Glass Orchard",
    description: "An anomaly grove where frozen figures bloom from the road.",
    risk: 5,
    hours: 5,
    encounterChance: 0.48,
    enemies: ["stalker", "static_touched"],
    loot: { water: [1, 2], parts: [4, 6], electronics: [0, 1], morale: [1, 2], relics: [1, 3] },
    itemPool: ["signal_cloak", "odd_relic"],
    itemChance: 0.28,
  },
  {
    id: "hidden_bunker_entrance",
    name: "Hidden Bunker Entrance",
    description: "A concrete mouth under the city, still pretending not to exist.",
    risk: 6,
    hours: 5,
    encounterChance: 0.56,
    enemies: ["static_touched", "relay_brute"],
    loot: { scrap: [8, 12], parts: [6, 10], wire: [2, 4], electronics: [1, 2], reputation: [3, 5], relics: [2, 4] },
    itemPool: ["bunker_pass", "fire_axe"],
    itemChance: 0.32,
  },
];

export const ZONES_BY_ID = Object.fromEntries(ZONES.map((zone) => [zone.id, zone]));

export const FACTIONS = [
  {
    id: "signal_hunters",
    name: "Signal Hunters",
    description: "Patient scavengers of towers, frequencies, and truths.",
    bonuses: ["Directed radio sweeps build traces faster", "Hunter exchange opens signal-heavy deals", "Signal objectives pull deeper tech"],
    costs: ["Hotter signal work raises noise and raid attention"],
    effects: { radioDepth: 0.5, signalGain: 0.42, expeditionLootBonus: 0.05, traderDiscount: 0.04 },
    consequences: {
      tradeChannel: "hunter_exchange",
      objectiveBias: { signal: 0.16 },
      nightNoise: 0.25,
      raidBias: 0.04,
    },
  },
  {
    id: "iron_lantern",
    name: "Iron Lantern",
    description: "Militant keepers of lit ground and strict borders.",
    bonuses: ["Night defense and breach control improve immediately", "Lantern depot opens arms and medical stock", "Guards hit harder during pressure events"],
    costs: ["Anomaly tracing slows under their doctrine"],
    effects: { defense: 2, attack: 1, nightMitigation: 1.2 },
    consequences: {
      tradeChannel: "lantern_depot",
      raidMitigation: 0.14,
      breachMitigation: 0.1,
      anomalyPenalty: 0.2,
    },
  },
  {
    id: "ash_marauders",
    name: "Ash Marauders",
    description: "Mobile opportunists with a market ethic and bad manners.",
    bonuses: ["Hard pushes and sweep objectives return more salvage", "Broker channel favors ammo, caches, and ugly gear", "Close-quarters fighting gets meaner"],
    costs: ["Your shelter gets louder and raider attention climbs"],
    effects: { expeditionLootBonus: 0.15, attack: 1, salvageYieldBonus: 0.12, traderDiscount: 0.06 },
    consequences: {
      tradeChannel: "marauder_broker",
      objectiveBias: { salvage: 0.14, sweep: 0.12 },
      nightNoise: 0.35,
      raidBias: 0.08,
    },
  },
];

export const FACTIONS_BY_ID = Object.fromEntries(FACTIONS.map((faction) => [faction.id, faction]));

export const TRADER_CHANNELS = [
  {
    id: "open_market",
    name: "Open Market",
    description: "General traffic. Food, meds, loose wire, and whatever walks in without asking permission.",
    tag: "neutral",
  },
  {
    id: "hunter_exchange",
    name: "Hunter Exchange",
    description: "Signal Hunters trade in field tech, tower whispers, and relic-sensitive gear.",
    tag: "signal",
    requiresFaction: "signal_hunters",
  },
  {
    id: "lantern_depot",
    name: "Lantern Depot",
    description: "Iron Lantern stock runs military and defensive, priced like they know it.",
    tag: "defense",
    requiresFaction: "iron_lantern",
  },
  {
    id: "marauder_broker",
    name: "Marauder Broker",
    description: "Ash Marauders sell fast salvage, contraband rounds, and reckless routes.",
    tag: "salvage",
    requiresFaction: "ash_marauders",
  },
];

export const TRADER_CHANNELS_BY_ID = Object.fromEntries(TRADER_CHANNELS.map((channel) => [channel.id, channel]));

export const TRADER_OFFERS = [
  {
    id: "crate_meal",
    name: "Crate Meal",
    channels: ["open_market", "lantern_depot"],
    cost: { scrap: 14 },
    reward: { resources: { food: 3, water: 2, morale: 1 } },
    description: "Cans, jugs, and one good lie.",
  },
  {
    id: "field_meds",
    name: "Field Meds",
    channels: ["open_market", "lantern_depot"],
    cost: { scrap: 12, cloth: 1 },
    reward: { resources: { medicine: 2, chemicals: 1 }, grantItems: { bandage_roll: 1 } },
    description: "Bandages, pills, and no questions.",
  },
  {
    id: "wire_spool",
    name: "Wire Spool",
    channels: ["open_market", "hunter_exchange"],
    cost: { scrap: 10, parts: 1 },
    reward: { resources: { wire: 4, electronics: 1 } },
    description: "Insulated spool and one board still worth opening.",
  },
  {
    id: "tower_whisper",
    name: "Tower Whisper",
    channels: ["hunter_exchange"],
    cost: { fuel: 2, wire: 1, parts: 2 },
    reward: { resources: { reputation: 2 }, radioProgress: 1, radioTrace: { tower_grid: 1 } },
    description: "Directions spoken like a confession.",
  },
  {
    id: "loose_rounds",
    name: "Loose Rounds",
    channels: ["open_market", "marauder_broker"],
    cost: { scrap: 10, chemicals: 1, parts: 1 },
    reward: { resources: { ammo: 5 } },
    description: "Sorted by caliber, mostly.",
  },
  {
    id: "armor_bundle",
    name: "Armor Bundle",
    channels: ["lantern_depot"],
    cost: { scrap: 20, cloth: 2, parts: 4 },
    reward: { grantItems: { patchwork_vest: 1 } },
    description: "Cloth, leather, plates, and a lot of thread.",
  },
  {
    id: "rifle_cache",
    name: "Rifle Cache",
    channels: ["lantern_depot", "marauder_broker"],
    cost: { scrap: 24, ammo: 2, reputation: 2 },
    reward: { grantItems: { tower_rifle: 1 } },
    description: "Something long, cleaned, and hidden on purpose.",
  },
  {
    id: "relic_trade",
    name: "Relic Trade",
    channels: ["hunter_exchange"],
    cost: { relics: 1, scrap: 8 },
    reward: { resources: { fuel: 3, parts: 4, reputation: 1 } },
    description: "The lantern folk collect stranger things than you do.",
  },
  {
    id: "static_cloth",
    name: "Static Cloth",
    channels: ["hunter_exchange"],
    cost: { relics: 2, reputation: 2 },
    reward: { grantItems: { signal_cloak: 1 } },
    description: "Conductive fabric for people with bad priorities.",
  },
  {
    id: "breach_kit",
    name: "Breach Kit",
    channels: ["marauder_broker"],
    cost: { scrap: 18, parts: 3, fuel: 1 },
    reward: { resources: { ammo: 3, parts: 2 }, grantItems: { road_flare: 1 } },
    description: "Fast-entry tools and enough fire to leave fast too.",
  },
];

export const SCAVENGE_SOURCES = [
  {
    id: "rubble",
    label: "Search rubble",
    short: "RU",
    description: "Broken masonry, splintered frames, wet cloth, open pockets.",
    detail: "Balanced salvage with real shelter material in it. Cheap, quick, and no longer quiet if you lean on it too hard.",
    focus: ["Scrap", "Wood", "Drinkable Water"],
    tags: ["1h", "rising noise", "street debris"],
    hours: 1,
    threat: 0.42,
    noise: 0.52,
    scrapMod: { min: 0, max: 0 },
    directResources: {
      wood: [1, 1],
    },
    guaranteed: ["common"],
    rolls: [
      { rarity: "uncommon", chance: 0.74 },
      { rarity: "rare", chance: 0.16, rareBonus: 1 },
      { rarity: "epic", chance: 0.06, rareBonus: 0.45, requires: { searches: 10 } },
      { rarity: "legendary", chance: 0.025, rareBonus: 0.2, requires: { searches: 18 } },
      { rarity: "anomalous", chance: 0.018, rareBonus: 0.16, requires: { radioProgress: 4 } },
      { rarity: "mythic", chance: 0.012, rareBonus: 0.08, requires: { flags: ["worldReveal"] } },
    ],
    bonusChance: 0.58,
    rarityBias: { uncommon: 0.02, rare: 0.03 },
    logLabel: "the rubble",
    eventChance: 0.42,
  },
  {
    id: "vehicle_shells",
    label: "Strip vehicle shells",
    short: "VH",
    description: "Dash metal, fuel lines, batteries, and glovebox lies.",
    detail: "Better for parts, wire, and fuel. Slightly louder than rubble and worth it.",
    focus: ["Parts", "Fuel", "Wire"],
    tags: ["1h", "medium noise", "engine blocks"],
    hours: 1,
    threat: 0.48,
    noise: 0.72,
    scrapMod: { min: 0, max: 1 },
    directResources: {
      parts: [1, 2],
      fuel: [0, 1],
    },
    guaranteed: ["common", "uncommon"],
    rolls: [
      { rarity: "rare", chance: 0.24, rareBonus: 1.1 },
      { rarity: "epic", chance: 0.1, rareBonus: 0.5, requires: { upgrades: ["crafting_bench"] } },
      { rarity: "legendary", chance: 0.045, rareBonus: 0.24, requires: { upgrades: ["watch_post"] } },
      { rarity: "anomalous", chance: 0.014, rareBonus: 0.1, requires: { radioProgress: 4 } },
    ],
    bonusChance: 0.66,
    rarityBias: { rare: 0.04, epic: 0.03 },
    requires: { searches: 4 },
    logLabel: "the vehicle shells",
    eventChance: 0.46,
  },
  {
    id: "dead_pantries",
    label: "Check dead pantries",
    short: "PN",
    description: "Cupboards, kitchen sinks, old shelves, and sealed luck.",
    detail: "Reliable food and water lane. Low yield in scrap, high value when hunger starts talking.",
    focus: ["Food", "Drinkable Water", "Medicine"],
    tags: ["1h", "quiet", "food lane"],
    hours: 1,
    threat: 0.28,
    noise: 0.26,
    scrapMod: { min: -1, max: 0 },
    directResources: {
      food: [1, 2],
      water: [1, 1],
    },
    guaranteed: ["common", "uncommon"],
    rolls: [
      { rarity: "rare", chance: 0.18, rareBonus: 0.9 },
      { rarity: "epic", chance: 0.08, rareBonus: 0.36, requires: { upgrades: ["food_crate"] } },
      { rarity: "legendary", chance: 0.022, rareBonus: 0.14, requires: { upgrades: ["smokehouse"] } },
    ],
    bonusChance: 0.54,
    rarityBias: { uncommon: 0.05, rare: 0.02 },
    requires: { upgrades: ["food_search"] },
    logLabel: "the dead pantries",
    eventChance: 0.36,
  },
  {
    id: "clinic_drawers",
    label: "Sweep clinic drawers",
    short: "CL",
    description: "Cracked cabinets, labelled trays, and pills no one came back for.",
    detail: "Medicine lane. Slower to open up, but it starts paying in clean painkillers and better tools.",
    focus: ["Medicine", "Chemicals", "Cloth"],
    tags: ["1h", "medium noise", "medical lane"],
    hours: 1,
    threat: 0.38,
    noise: 0.58,
    scrapMod: { min: -1, max: 0 },
    directResources: {
      medicine: [1, 1],
      cloth: [0, 1],
    },
    guaranteed: ["common", "uncommon"],
    rolls: [
      { rarity: "rare", chance: 0.3, rareBonus: 1.15 },
      { rarity: "epic", chance: 0.12, rareBonus: 0.5, requires: { upgrades: ["crafting_bench"] } },
      { rarity: "legendary", chance: 0.035, rareBonus: 0.18, requires: { upgrades: ["smokehouse"] } },
    ],
    bonusChance: 0.6,
    rarityBias: { rare: 0.05, epic: 0.03 },
    requires: { upgrades: ["first_aid_rag"] },
    logLabel: "the clinic drawers",
    eventChance: 0.44,
  },
  {
    id: "signal_wrecks",
    label: "Trace signal wrecks",
    short: "SG",
    description: "Tower scrap, relay boxes, antenna guts, and static-burned hardware.",
    detail: "Electronics lane. Stronger upper rarity access once the radio is online.",
    focus: ["Wire", "Electronics", "Relics"],
    tags: ["2h", "high noise", "signal lane"],
    hours: 2,
    threat: 0.62,
    noise: 1.18,
    scrapMod: { min: -1, max: 0 },
    directResources: {
      wire: [1, 2],
      electronics: [1, 1],
    },
    guaranteed: ["uncommon"],
    rolls: [
      { rarity: "rare", chance: 0.34, rareBonus: 1.2 },
      { rarity: "epic", chance: 0.18, rareBonus: 0.62, requires: { radioProgress: 1 } },
      { rarity: "legendary", chance: 0.085, rareBonus: 0.34, requires: { radioProgress: 2 } },
      { rarity: "anomalous", chance: 0.05, rareBonus: 0.24, requires: { radioProgress: 4 } },
      { rarity: "mythic", chance: 0.018, rareBonus: 0.12, requires: { flags: ["worldReveal"] } },
    ],
    bonusChance: 0.72,
    rarityBias: { epic: 0.05, legendary: 0.04, anomalous: 0.03 },
    requires: { upgrades: ["radio_rig"] },
    logLabel: "the signal wrecks",
    eventChance: 0.54,
  },
  {
    id: "sealed_caches",
    label: "Crack sealed caches",
    short: "SC",
    description: "Locked service cases, ammo tins, and someone else's emergency plan.",
    detail: "Late mid-game cache lane. Costs more threat and needs a pry bar, but pays with gear and upper-tier hardware.",
    focus: ["Ammo", "Parts", "Gear"],
    tags: ["2h", "high noise", "sealed stock"],
    hours: 2,
    threat: 0.72,
    noise: 1.34,
    scrapMod: { min: 0, max: 1 },
    directResources: {
      parts: [1, 2],
      ammo: [1, 2],
    },
    guaranteed: ["uncommon"],
    rolls: [
      { rarity: "rare", chance: 0.36, rareBonus: 1.2 },
      { rarity: "epic", chance: 0.2, rareBonus: 0.65, requires: { upgrades: ["crafting_bench"] } },
      { rarity: "legendary", chance: 0.12, rareBonus: 0.42, requires: { upgrades: ["watch_post"] } },
      { rarity: "anomalous", chance: 0.038, rareBonus: 0.2, requires: { secretProgress: 1 } },
      { rarity: "mythic", chance: 0.02, rareBonus: 0.12, requires: { flags: ["worldReveal"] } },
    ],
    bonusChance: 0.7,
    rarityBias: { rare: 0.03, epic: 0.06, legendary: 0.05 },
    requires: { upgrades: ["watch_post", "crafting_bench"], items: ["pry_bar"] },
    logLabel: "the sealed caches",
    eventChance: 0.58,
  },
];

export const SCAVENGE_SOURCES_BY_ID = Object.fromEntries(SCAVENGE_SOURCES.map((source) => [source.id, source]));

export const EXPEDITION_APPROACHES = [
  {
    id: "cautious",
    label: "Cautious",
    short: "quiet route",
    description: "Move slow, skip bad angles, and bring enough to wait things out.",
    cost: { food: 1, water: 1 },
    hours: 1,
    encounterDelta: -0.18,
    lootBonus: -0.1,
    threat: 0.08,
    noise: 0.12,
    travelEventChance: 0.28,
  },
  {
    id: "standard",
    label: "Standard",
    short: "balanced route",
    description: "The middle path. Not elegant. Usually survivable.",
    cost: {},
    hours: 0,
    encounterDelta: 0,
    lootBonus: 0,
    threat: 0.34,
    noise: 0.48,
    travelEventChance: 0.38,
  },
  {
    id: "forced",
    label: "Forced",
    short: "fast and loud",
    description: "Push hard, break locks, and accept that everything hears you.",
    cost: { water: 1, fuel: 1, ammo: 1 },
    hours: -1,
    encounterDelta: 0.16,
    lootBonus: 0.12,
    threat: 0.78,
    noise: 1.18,
    travelEventChance: 0.58,
  },
];

export const EXPEDITION_APPROACHES_BY_ID = Object.fromEntries(EXPEDITION_APPROACHES.map((approach) => [approach.id, approach]));

export const EXPEDITION_OBJECTIVES = [
  {
    id: "salvage",
    label: "Salvage",
    short: "metal + parts",
    description: "Strip weight, pry hardware, and come back heavier than you left.",
    resourceBias: { scrap: 0.3, parts: 0.18, wire: 0.1, fuel: 0.08 },
    itemChanceBonus: 0.02,
    encounterDelta: 0.06,
    hours: 0,
    threat: 0.14,
    noise: 0.18,
    tags: ["yield", "parts", "louder"],
  },
  {
    id: "provisions",
    label: "Provisions",
    short: "food + water",
    description: "Aim for cupboards, clean water, and anything that keeps the room fed.",
    resourceBias: { food: 0.36, water: 0.26, cloth: 0.1, medicine: 0.06 },
    itemChanceBonus: 0.02,
    encounterDelta: -0.08,
    hours: 0,
    threat: -0.08,
    noise: -0.12,
    tags: ["safer", "food", "water"],
  },
  {
    id: "medicine",
    label: "Medicine",
    short: "meds + chems",
    description: "Push into cabinets, triage rooms, and cold storage looking for clean help.",
    resourceBias: { medicine: 0.46, chemicals: 0.28, water: 0.08, cloth: 0.08 },
    itemChanceBonus: 0.05,
    encounterDelta: 0.05,
    hours: 1,
    threat: 0.1,
    noise: 0.06,
    tags: ["slow", "medical", "clean"],
  },
  {
    id: "signal",
    label: "Signal",
    short: "tech + clues",
    description: "Chase relay boxes, tower residue, and strange hardware with a pulse still in it.",
    resourceBias: { wire: 0.16, electronics: 0.28, reputation: 0.16, relics: 0.1, parts: 0.1 },
    itemChanceBonus: 0.08,
    encounterDelta: 0.08,
    hours: 1,
    threat: 0.18,
    noise: 0.2,
    traceGain: { tower_grid: 1.2, anomaly_trace: 0.7 },
    tags: ["tech", "clues", "hot"],
  },
  {
    id: "sweep",
    label: "Sweep",
    short: "fight + caches",
    description: "Push hard, clear movement, and accept that the route may turn into a brawl.",
    resourceBias: { ammo: 0.24, parts: 0.18, scrap: 0.12, relics: 0.08 },
    itemChanceBonus: 0.1,
    encounterDelta: 0.16,
    hours: -1,
    threat: 0.26,
    noise: 0.3,
    combatBonus: 1,
    tags: ["combat", "fast", "cache"],
  },
];

export const EXPEDITION_OBJECTIVES_BY_ID = Object.fromEntries(EXPEDITION_OBJECTIVES.map((objective) => [objective.id, objective]));

export const RADIO_INVESTIGATIONS = [
  {
    id: "civic_band",
    label: "Civic Band",
    short: "archive traffic",
    description: "Sweep old emergency channels, public dispatch, and evacuation spillover.",
    traceLabel: "Archive trace",
    milestones: [
      {
        id: "civic_dispatch",
        at: 1,
        text: "Archive traffic resolves into a calm evacuation countdown and a hospital wing repeating under it.",
        effects: { radioProgress: 1, resources: { reputation: 1 }, unlockZones: ["hospital_wing"] },
      },
      {
        id: "civic_market",
        at: 3,
        text: "Price codes and lantern marks bleed into the civic band, but the real value is the route chatter hiding under them.",
        effects: { radioProgress: 1, resources: { reputation: 1, parts: 1 } },
      },
      {
        id: "civic_rumor",
        at: 5,
        text: "The old city band knows route names the living are still using. Someone kept listening after everyone else stopped.",
        effects: { radioProgress: 1, resources: { reputation: 2 } },
      },
    ],
  },
  {
    id: "tower_grid",
    label: "Tower Grid",
    short: "tower relays",
    description: "Triangulate tower relay bursts and the channels built to carry them.",
    traceLabel: "Tower trace",
    milestones: [
      {
        id: "tower_perimeter",
        at: 1,
        text: "A clipped tower handoff maps the perimeter and proves the fence still talks when it should be dead.",
        effects: { radioProgress: 1, unlockZones: ["radio_tower_perimeter"] },
      },
      {
        id: "tower_cells",
        at: 3,
        text: "The tower grid starts naming its own maintenance cells. There are more hands on the signal than you thought.",
        effects: { radioProgress: 1, resources: { electronics: 1, reputation: 1 }, secretProgress: 1 },
      },
      {
        id: "tower_hunters",
        at: 5,
        text: "Signal Hunters stop sounding like rumor and start sounding like a coordinated network sitting right on top of the grid.",
        effects: { radioProgress: 1, resources: { reputation: 3 } },
      },
    ],
  },
  {
    id: "sublevel_echo",
    label: "Sublevel Echo",
    short: "maintenance routes",
    description: "Track maintenance routes, drowned service lines, and concrete that still breathes on the band.",
    traceLabel: "Sublevel trace",
    milestones: [
      {
        id: "sublevel_tunnel",
        at: 1,
        text: "Flood-control calls line up into a maintenance route beneath the streets.",
        effects: { radioProgress: 1, unlockZones: ["flooded_tunnel"] },
      },
      {
        id: "sublevel_breath",
        at: 3,
        text: "A sealed air-handling loop opens for a second, then cuts out before you can answer it.",
        effects: { secretProgress: 1 },
      },
      {
        id: "sublevel_bunker",
        at: 5,
        text: "The sublevel pattern repeats around a hardened door schedule. There is a bunker route under the city after all.",
        effects: { radioProgress: 1, secretProgress: 1, setFlags: { bunkerRouteKnown: true }, unlockZones: ["hidden_bunker_entrance"] },
      },
    ],
  },
  {
    id: "anomaly_trace",
    label: "Anomaly Trace",
    short: "impossible carrier",
    description: "Push past archive noise and track the places where static behaves like a living system.",
    traceLabel: "Anomaly trace",
    milestones: [
      {
        id: "anomaly_orchard",
        at: 1,
        text: "A child's voice keeps naming a place called the Glass Orchard like it expects you to know the way.",
        effects: { secretProgress: 1, unlockZones: ["glass_orchard"] },
      },
      {
        id: "anomaly_relic",
        at: 3,
        text: "The trace stabilizes long enough to pull a relic-bearing carrier out of the hiss.",
        effects: { radioProgress: 1, resources: { relics: 1 } },
      },
      {
        id: "anomaly_dead_static",
        at: 5,
        text: "The anomaly layer stops acting like weather and starts acting like infrastructure. The static was built.",
        effects: { radioProgress: 1, secretProgress: 1 },
      },
    ],
  },
];

export const RADIO_INVESTIGATIONS_BY_ID = Object.fromEntries(RADIO_INVESTIGATIONS.map((investigation) => [investigation.id, investigation]));

export const SEARCH_LOOT_TABLE = [
  {
    id: "loot_scrap",
    type: "resource",
    key: "scrap",
    amount: [1, 3],
    rarity: "common",
    weight: 28,
  },
  {
    id: "loot_cloth",
    type: "resource",
    key: "cloth",
    amount: [1, 2],
    rarity: "common",
    weight: 18,
  },
  {
    id: "loot_water",
    type: "resource",
    key: "water",
    amount: [1, 2],
    rarity: "common",
    weight: 16,
  },
  {
    id: "loot_food",
    type: "resource",
    key: "food",
    amount: [1, 2],
    rarity: "uncommon",
    weight: 12,
    sources: ["dead_pantries"],
  },
  {
    id: "loot_parts",
    type: "resource",
    key: "parts",
    amount: [1, 2],
    rarity: "uncommon",
    weight: 12,
    sources: ["vehicle_shells", "sealed_caches"],
  },
  {
    id: "loot_wire",
    type: "resource",
    key: "wire",
    amount: [1, 2],
    rarity: "uncommon",
    weight: 9,
    sources: ["rubble", "vehicle_shells", "signal_wrecks"],
  },
  {
    id: "loot_fuel",
    type: "resource",
    key: "fuel",
    amount: [1, 1],
    rarity: "uncommon",
    weight: 8,
    sources: ["vehicle_shells", "sealed_caches"],
  },
  {
    id: "loot_beans",
    type: "item",
    key: "canned_beans",
    amount: [1, 1],
    rarity: "uncommon",
    weight: 6,
    sources: ["dead_pantries"],
  },
  {
    id: "loot_cloth_bundle",
    type: "resource",
    key: "cloth",
    amount: [2, 3],
    rarity: "uncommon",
    weight: 5,
    requires: { searches: 5 },
    sources: ["rubble", "dead_pantries", "clinic_drawers"],
  },
  {
    id: "loot_medicine",
    type: "resource",
    key: "medicine",
    amount: [1, 1],
    rarity: "rare",
    weight: 5,
    sources: ["dead_pantries", "clinic_drawers"],
  },
  {
    id: "loot_ammo",
    type: "resource",
    key: "ammo",
    amount: [1, 2],
    rarity: "rare",
    weight: 4,
    sources: ["sealed_caches"],
  },
  {
    id: "loot_electronics",
    type: "resource",
    key: "electronics",
    amount: [1, 1],
    rarity: "rare",
    weight: 4,
    sources: ["signal_wrecks", "sealed_caches"],
  },
  {
    id: "loot_chemicals",
    type: "resource",
    key: "chemicals",
    amount: [1, 1],
    rarity: "rare",
    weight: 4,
    sources: ["clinic_drawers", "vehicle_shells"],
  },
  {
    id: "loot_sharp_metal",
    type: "item",
    key: "sharp_metal",
    amount: [1, 1],
    rarity: "rare",
    weight: 3,
    sources: ["rubble", "vehicle_shells"],
  },
  {
    id: "loot_bandage_roll",
    type: "item",
    key: "bandage_roll",
    amount: [1, 1],
    rarity: "rare",
    weight: 2,
    requires: { searches: 8 },
    sources: ["clinic_drawers", "dead_pantries"],
  },
  {
    id: "loot_road_flare",
    type: "item",
    key: "road_flare",
    amount: [1, 1],
    rarity: "rare",
    weight: 3,
    requires: { searches: 6 },
    sources: ["vehicle_shells"],
  },
  {
    id: "loot_field_filter",
    type: "item",
    key: "field_filter",
    amount: [1, 1],
    rarity: "rare",
    weight: 3,
    requires: { upgrades: ["food_search"] },
    sources: ["dead_pantries", "clinic_drawers"],
  },
  {
    id: "loot_fuel_cell",
    type: "item",
    key: "fuel_cell",
    amount: [1, 1],
    rarity: "epic",
    weight: 4,
    requires: { searches: 10 },
    sources: ["vehicle_shells", "sealed_caches"],
  },
  {
    id: "loot_clinic_case",
    type: "item",
    key: "clinic_case",
    amount: [1, 1],
    rarity: "epic",
    weight: 3,
    requires: { upgrades: ["first_aid_rag", "crafting_bench"] },
    sources: ["clinic_drawers"],
  },
  {
    id: "loot_electronics_cache",
    type: "resource",
    key: "electronics",
    amount: [2, 3],
    rarity: "epic",
    weight: 3,
    requires: { upgrades: ["crafting_bench"] },
    sources: ["signal_wrecks", "sealed_caches"],
  },
  {
    id: "loot_pry_bar",
    type: "item",
    key: "pry_bar",
    amount: [1, 1],
    rarity: "epic",
    weight: 3,
    requires: { searches: 12, upgrades: ["crafting_bench"] },
    sources: ["rubble", "vehicle_shells", "sealed_caches"],
  },
  {
    id: "loot_coil_spike",
    type: "item",
    key: "coil_spike",
    amount: [1, 1],
    rarity: "epic",
    weight: 2,
    requires: { radioProgress: 1, upgrades: ["crafting_bench"] },
    sources: ["signal_wrecks"],
  },
  {
    id: "loot_patchwork_vest",
    type: "item",
    key: "patchwork_vest",
    amount: [1, 1],
    rarity: "legendary",
    weight: 2,
    requires: { searches: 16, upgrades: ["armor_hooks"] },
    sources: ["sealed_caches"],
  },
  {
    id: "loot_transit_pistol",
    type: "item",
    key: "transit_pistol",
    amount: [1, 1],
    rarity: "legendary",
    weight: 2,
    requires: { searches: 16, upgrades: ["weapon_rack"] },
    sources: ["sealed_caches"],
  },
  {
    id: "loot_tower_battery",
    type: "item",
    key: "tower_battery",
    amount: [1, 1],
    rarity: "legendary",
    weight: 2,
    requires: { radioProgress: 2, upgrades: ["radio_rig"] },
    sources: ["signal_wrecks"],
  },
  {
    id: "loot_relics",
    type: "resource",
    key: "relics",
    amount: [1, 1],
    rarity: "legendary",
    weight: 3,
    requires: { radioProgress: 4 },
    sources: ["signal_wrecks"],
  },
  {
    id: "loot_odd_relic",
    type: "item",
    key: "odd_relic",
    amount: [1, 1],
    rarity: "anomalous",
    weight: 2,
    requires: { secretProgress: 2 },
    sources: ["signal_wrecks"],
  },
  {
    id: "loot_static_lens",
    type: "item",
    key: "static_lens",
    amount: [1, 1],
    rarity: "mythic",
    weight: 1,
    requires: { flags: ["worldReveal"] },
    sources: ["signal_wrecks"],
  },
];
