export const SAVE_KEY = "dead-static-save-v2";

export const RESOURCE_ORDER = [
  "scrap",
  "wood",
  "food",
  "water",
  "cloth",
  "fuel",
  "parts",
  "wire",
  "medicine",
  "ammo",
  "electronics",
  "chemicals",
  "morale",
  "reputation",
  "relics",
];

export const RESOURCE_DEFS = {
  scrap: { label: "Scrap", tier: "core" },
  wood: { label: "Wood", tier: "core" },
  food: { label: "Food", tier: "core" },
  water: { label: "Drinkable Water", tier: "core" },
  cloth: { label: "Cloth", tier: "common" },
  fuel: { label: "Fuel", tier: "uncommon" },
  parts: { label: "Parts", tier: "uncommon" },
  wire: { label: "Wire", tier: "uncommon" },
  medicine: { label: "Medicine", tier: "rare" },
  ammo: { label: "Ammo", tier: "rare" },
  electronics: { label: "Electronics", tier: "rare" },
  chemicals: { label: "Chemicals", tier: "rare" },
  morale: { label: "Morale", tier: "social" },
  reputation: { label: "Reputation", tier: "social" },
  relics: { label: "Relics", tier: "mythic" },
};

export const RARITY_ORDER = ["common", "uncommon", "rare", "epic", "legendary", "anomalous", "mythic"];

export const RARITY_DEFS = {
  common: {
    label: "Common",
    hint: "easy salvage",
  },
  uncommon: {
    label: "Uncommon",
    hint: "worth checking twice",
  },
  rare: {
    label: "Rare",
    hint: "good days and locked cabinets",
  },
  epic: {
    label: "Epic",
    hint: "deep salvage and worthwhile risk",
  },
  legendary: {
    label: "Signal-Bound",
    hint: "sealed stock and city-grade hardware",
  },
  anomalous: {
    label: "Anomalous",
    hint: "found where the static gets physical",
  },
  mythic: {
    label: "Pre-Fall Prototype",
    hint: "the city still hiding impossible machines",
  },
};

export const SURVIVOR_ROLES = {
  scavenger: {
    label: "Scavenger",
    description: "Pulls slow salvage from the nearby bones of the city.",
  },
  guard: {
    label: "Guard",
    description: "Turns a weak shelter into a defended one.",
  },
  medic: {
    label: "Medic",
    description: "Stretches medicine and keeps condition losses manageable.",
  },
  scout: {
    label: "Scout",
    description: "Improves expedition yields and escape odds.",
  },
  tuner: {
    label: "Tuner",
    description: "Listens deeper into the static and finds better routes.",
  },
};

export const SURVIVOR_NAME_POOL = [
  "Mara Vale",
  "Jonah Wren",
  "Petra Voss",
  "Ilan Cross",
  "Tessa Bloom",
  "Rook Mercer",
  "Nadia Pike",
  "Vale Mercer",
  "Iris Flint",
  "Milan Dusk",
  "Orin Pike",
  "Cora Ash",
  "Toma Redd",
  "Lena Wex",
  "Riva Thorn",
  "Niko Slate",
  "Jessa Vale",
  "Bram Kest",
  "Ana Drift",
  "Miro Sable",
  "Rhea Crow",
  "Luka Morn",
  "Dara Venn",
  "Tarin Fox",
];

export const SURVIVOR_TRAITS = {
  quiet_hands: {
    label: "Quiet Hands",
    role: "scavenger",
    summary: "Pulls cleaner salvage and keeps nearby lanes quieter.",
  },
  pack_rat: {
    label: "Pack Rat",
    role: "scavenger",
    summary: "Turns salvage-heavy runs into better scrap and parts returns.",
  },
  hard_case: {
    label: "Hard Case",
    role: "guard",
    summary: "Blunts night damage and holds the line when the fence shakes.",
  },
  lantern_nerve: {
    label: "Lantern Nerve",
    role: "guard",
    summary: "Keeps morale from dropping when nights get loud.",
  },
  patch_saint: {
    label: "Patch Saint",
    role: "medic",
    summary: "Makes medical work stretch further than it should.",
  },
  bone_saw: {
    label: "Bone Saw",
    role: "medic",
    summary: "Trades comfort for efficient recovery and ugly field care.",
  },
  pathfinder: {
    label: "Pathfinder",
    role: "scout",
    summary: "Reads routes better, cuts encounter odds, and spots exits faster.",
  },
  breaker: {
    label: "Breaker",
    role: "scout",
    summary: "Best on hard pushes, fast breaches, and violent sweeps.",
  },
  ghost_ear: {
    label: "Ghost Ear",
    role: "tuner",
    summary: "Builds directed radio traces faster than static should allow.",
  },
  odd_frequency: {
    label: "Odd Frequency",
    role: "tuner",
    summary: "Finds anomaly traces quickly but leaves everyone slightly on edge.",
  },
};

export const ITEMS = {
  sharp_metal: {
    id: "sharp_metal",
    name: "Sharp Metal",
    type: "material",
    description: "Craft material for blades, bars, and improvised tools.",
  },
  backpack: {
    id: "backpack",
    name: "Backpack",
    type: "backpack",
    tier: "field",
    searchBonusRolls: 1,
    searchScrapMin: 1,
    salvageYieldBonus: 0.05,
    description: "Pack. Adds one extra salvage roll, raises your scrap floor, and lets you carry more out of short runs.",
  },
  rusty_knife: {
    id: "rusty_knife",
    name: "Rusty Knife",
    type: "weapon",
    tier: "improvised",
    attack: 3,
    description: "Weapon. Attack 3.",
  },
  pry_bar: {
    id: "pry_bar",
    name: "Pry Bar",
    type: "tool",
    toolRole: "salvage",
    description: "Tool. Opens sealed caches and improves parts salvage.",
  },
  hammer: {
    id: "hammer",
    name: "Hammer",
    type: "tool",
    toolRole: "build",
    description: "Tool. Required for structural builds and blunt weapon assembly.",
  },
  sewing_kit: {
    id: "sewing_kit",
    name: "Sewing Kit",
    type: "tool",
    toolRole: "clothwork",
    description: "Tool. Required for backpacks, cloth repairs, and stitched armor work.",
  },
  salvage_hatchet: {
    id: "salvage_hatchet",
    name: "Salvage Hatchet",
    type: "tool",
    toolRole: "salvage",
    description: "Tool. Improves wood recovery and shelter work.",
  },
  sharpening_stone: {
    id: "sharpening_stone",
    name: "Sharpening Stone",
    type: "tool",
    toolRole: "edgework",
    description: "Tool. Required for better blade and spear work.",
  },
  carpenter_kit: {
    id: "carpenter_kit",
    name: "Carpenter Kit",
    type: "tool",
    toolRole: "build",
    description: "Tool. Improves repairs and maintenance.",
  },
  hand_drill: {
    id: "hand_drill",
    name: "Hand Drill",
    type: "tool",
    toolRole: "repair",
    description: "Tool. Improves parts salvage, repairs, and signal rig work.",
  },
  signal_meter: {
    id: "signal_meter",
    name: "Signal Meter",
    type: "tool",
    toolRole: "signal",
    description: "Tool. Improves signal and anomaly trace work.",
  },
  nail_bat: {
    id: "nail_bat",
    name: "Nail Bat",
    type: "weapon",
    tier: "bench-made",
    attack: 5,
    description: "Weapon. Attack 5.",
  },
  hunting_spear: {
    id: "hunting_spear",
    name: "Hunting Spear",
    type: "weapon",
    tier: "bench-made",
    attack: 6,
    description: "Weapon. Attack 6.",
  },
  transit_pistol: {
    id: "transit_pistol",
    name: "Transit Pistol",
    type: "weapon",
    tier: "recovered",
    attack: 4,
    ammoPerAttack: 1,
    description: "Weapon. Attack 4. Uses 1 ammo.",
  },
  tower_rifle: {
    id: "tower_rifle",
    name: "Tower Rifle",
    type: "weapon",
    tier: "military",
    attack: 6,
    ammoPerAttack: 1,
    description: "Weapon. Attack 6. Uses 1 ammo.",
  },
  fire_axe: {
    id: "fire_axe",
    name: "Fire Axe",
    type: "weapon",
    tier: "heavy",
    attack: 7,
    description: "Weapon. Attack 7.",
  },
  patchwork_vest: {
    id: "patchwork_vest",
    name: "Patchwork Vest",
    type: "armor",
    tier: "stitched",
    defense: 2,
    description: "Armor. Defense 2.",
  },
  riot_padding: {
    id: "riot_padding",
    name: "Riot Padding",
    type: "armor",
    tier: "reinforced",
    defense: 3,
    description: "Armor. Defense 3.",
  },
  signal_cloak: {
    id: "signal_cloak",
    name: "Signal Cloak",
    type: "armor",
    tier: "signal",
    defense: 2,
    description: "Armor. Defense 2. Useful on signal-heavy runs.",
  },
  first_aid_rag: {
    id: "first_aid_rag",
    name: "First Aid Rag",
    type: "consumable",
    heal: 14,
    description: "Consumable. Heal 14.",
  },
  bandage_roll: {
    id: "bandage_roll",
    name: "Bandage Roll",
    type: "consumable",
    heal: 22,
    description: "Consumable. Heal 22.",
  },
  canned_beans: {
    id: "canned_beans",
    name: "Canned Beans",
    type: "consumable",
    condition: 6,
    resources: { food: 1 },
    description: "Consumable. Food +1 and Condition +6.",
  },
  fuel_cell: {
    id: "fuel_cell",
    name: "Fuel Cell",
    type: "consumable",
    resources: { fuel: 2 },
    description: "Consumable. Fuel +2.",
  },
  road_flare: {
    id: "road_flare",
    name: "Road Flare",
    type: "consumable",
    condition: 4,
    resources: { morale: 1 },
    description: "Consumable. Morale +1 and Condition +4.",
  },
  field_filter: {
    id: "field_filter",
    name: "Field Filter",
    type: "consumable",
    condition: 4,
    resources: { water: 2 },
    description: "Consumable. Drinkable Water +2 and Condition +4.",
  },
  clinic_case: {
    id: "clinic_case",
    name: "Clinic Case",
    type: "consumable",
    heal: 18,
    resources: { medicine: 1 },
    description: "Consumable. Heal 18 and Medicine +1.",
  },
  coil_spike: {
    id: "coil_spike",
    name: "Coil Spike",
    type: "weapon",
    attack: 5,
    description: "Weapon. Attack 5.",
  },
  tower_battery: {
    id: "tower_battery",
    name: "Tower Battery",
    type: "consumable",
    resources: { electronics: 2, fuel: 1 },
    description: "Consumable. Electronics +2 and Fuel +1.",
  },
  odd_relic: {
    id: "odd_relic",
    name: "Odd Relic",
    type: "key",
    description: "Key item for anomaly progress and late trades.",
  },
  relay_key: {
    id: "relay_key",
    name: "Relay Key",
    type: "key",
    description: "Key item for relay and sublevel progression.",
  },
  bunker_pass: {
    id: "bunker_pass",
    name: "Bunker Pass",
    type: "key",
    description: "Key item for bunker access.",
  },
  static_lens: {
    id: "static_lens",
    name: "Static Lens",
    type: "key",
    description: "Key item for anomaly route decoding.",
  },
};

export const ITEM_ORDER = Object.keys(ITEMS);
