export const EVENTS = [
  {
    id: "search_broken_meter",
    pool: "search",
    weight: 10,
    text: "A broken parking meter gives up a fistful of coins and screws.",
    effects: { resources: { scrap: 2 } },
  },
  {
    id: "search_soup_tin",
    pool: "search",
    weight: 8,
    text: "Under cracked plaster: a dented tin with something that still counts as food.",
    effects: { resources: { food: 1 }, discoverResources: ["food"] },
  },
  {
    id: "search_loose_copper",
    pool: "search",
    weight: 7,
    text: "A wall peels back and exposes copper the city forgot to protect.",
    effects: { resources: { wire: 1, parts: 1 }, discoverResources: ["wire", "parts"] },
  },
  {
    id: "search_alarm",
    pool: "search",
    weight: 6,
    text: "An old alarm screams once when you move the rubble. So do you.",
    effects: { resources: { scrap: 1 }, condition: -3 },
  },
  {
    id: "search_blanket",
    pool: "search",
    weight: 6,
    text: "Half a burnt blanket and a lighter. Good enough for a colder plan.",
    effects: { resources: { fuel: 1, cloth: 1 }, discoverResources: ["fuel", "cloth"] },
  },
  {
    id: "search_clinic_token",
    pool: "search",
    weight: 5,
    text: "A clinic drawer gives you alcohol wipes and a shiver.",
    effects: { resources: { medicine: 1 }, discoverResources: ["medicine"] },
  },
  {
    id: "search_torn_canvas",
    pool: "search",
    weight: 5,
    text: "A bus seat tears clean. The cloth and straps survive better than the passengers did.",
    effects: { resources: { cloth: 2 }, discoverResources: ["cloth"] },
  },
  {
    id: "search_sharp_metal",
    pool: "search",
    weight: 5,
    text: "A bent road sign snaps along a clean edge. One side is suddenly useful.",
    effects: { grantItems: { sharp_metal: 1 } },
  },
  {
    id: "search_satchel",
    pool: "search",
    weight: 4,
    text: "A school satchel survives with one unopened can inside.",
    effects: { grantItems: { canned_beans: 1 } },
  },
  {
    id: "search_funny_poster",
    pool: "search",
    weight: 4,
    text: "You find a poster that says STAY CALM in six torn pieces. Funny enough.",
    effects: { condition: 1 },
  },
  {
    id: "search_transistor",
    pool: "search",
    weight: 3,
    text: "A pocket transistor spits a second of speech before dying again.",
    effects: { resources: { parts: 1, electronics: 1 }, radioProgress: 1, discoverResources: ["parts", "electronics"] },
  },
  {
    id: "search_neighbor",
    pool: "search",
    weight: 3,
    text: "A dead neighbor still has a keyring and a note that says 'don't trust the tower'.",
    effects: { resources: { scrap: 1, parts: 1 }, discoverResources: ["parts"] },
  },
  {
    id: "food_cellar_jar",
    pool: "food",
    weight: 8,
    text: "Behind a broken cabinet: preserved vegetables gone soft but not hostile.",
    effects: { resources: { food: 2 } },
  },
  {
    id: "food_rat_run",
    pool: "food",
    weight: 6,
    text: "You corner a rat and lose some dignity catching dinner.",
    effects: { resources: { food: 2 }, condition: -2 },
  },
  {
    id: "food_rooftop_greens",
    pool: "food",
    weight: 4,
    text: "Someone once grew herbs on a roof. Something still grows there.",
    effects: { resources: { food: 1, morale: 1 } },
  },
  {
    id: "food_mold_bin",
    pool: "food",
    weight: 4,
    text: "A whole crate, ruined except for one sealed corner.",
    effects: { resources: { food: 1, morale: -1 } },
  },
  {
    id: "travel_cautious_drain",
    pool: "travel:cautious",
    weight: 6,
    text: "You wait out movement in a stairwell and arrive later, but not noticed.",
    effects: { condition: 1 },
  },
  {
    id: "travel_cautious_cache",
    pool: "travel:cautious",
    weight: 4,
    text: "Moving slow lets you spot a tucked-away service locker on the way.",
    effects: { resources: { parts: 1, water: 1 }, discoverResources: ["parts", "water"] },
  },
  {
    id: "travel_standard_detour",
    pool: "travel:standard",
    weight: 6,
    text: "A collapsed stairwell forces a detour through old offices and scattered files.",
    effects: { resources: { cloth: 1, scrap: 1 }, discoverResources: ["cloth"] },
  },
  {
    id: "travel_standard_standoff",
    pool: "travel:standard",
    weight: 4,
    text: "You freeze while something sniffs the air two rooms away, then move when it loses interest.",
    effects: { condition: -1 },
  },
  {
    id: "travel_forced_break",
    pool: "travel:forced",
    weight: 6,
    text: "You smash a chain latch to save time. The echo buys speed and future problems.",
    effects: { resources: { scrap: 1 }, condition: -2 },
  },
  {
    id: "travel_forced_score",
    pool: "travel:forced",
    weight: 4,
    text: "The loud route pays once: an exposed supply crate left where caution would miss it.",
    effects: { resources: { ammo: 1, parts: 1 }, discoverResources: ["ammo", "parts"] },
  },
  {
    id: "night_first",
    pool: "night",
    weight: 10,
    once: true,
    text: "First night. Every scrape outside sounds deliberate.",
    effects: { condition: -5, resources: { morale: -1 }, setFlags: { firstNightResolved: true } },
  },
  {
    id: "night_boards_hold",
    pool: "night",
    weight: 7,
    text: "Something tests the barricade, then loses interest or patience.",
    effects: { condition: 2 },
  },
  {
    id: "night_fingers_under_door",
    pool: "night",
    weight: 6,
    text: "Fingers feel along the gap under the door. You don't breathe until dawn.",
    effects: { condition: -3, resources: { morale: -1 } },
  },
  {
    id: "night_warm_embers",
    pool: "night",
    weight: 5,
    requires: { upgrades: ["campfire"] },
    text: "The fire burns low and steady. For one hour, the world stays outside.",
    effects: { condition: 3, resources: { morale: 1 } },
  },
  {
    id: "night_raider_shadow",
    pool: "night",
    weight: 4,
    requires: { day: 5 },
    text: "A lantern flash, hushed swearing, boots fading into alleys. Raiders are testing routes.",
    effects: { resources: { reputation: 1 }, secretProgress: 1 },
  },
  {
    id: "night_choir_dream",
    pool: "night",
    weight: 3,
    requires: { radioProgress: 3 },
    text: "You dream in station IDs and wake with your teeth aching.",
    effects: { condition: -2, radioProgress: 1 },
  },
  {
    id: "radio_numbers_station",
    pool: "radio",
    weight: 9,
    once: true,
    text: "A calm voice counts down to an evacuation that never came.",
    effects: { radioProgress: 1, resources: { reputation: 1 }, unlockSections: ["radio"] },
  },
  {
    id: "radio_drowned_dispatch",
    pool: "radio",
    weight: 8,
    once: true,
    text: "A waterlogged dispatch mentions maintenance routes beneath the city.",
    effects: { radioProgress: 1, unlockZones: ["flooded_tunnel"] },
  },
  {
    id: "radio_hospital_page",
    pool: "radio",
    weight: 7,
    once: true,
    text: "An endless hospital page repeats a wing number long after staff stopped answering.",
    effects: { radioProgress: 1, unlockZones: ["hospital_wing"] },
  },
  {
    id: "radio_tower_offer",
    pool: "radio",
    weight: 6,
    once: true,
    text: "A clipped transmission offers safe passage near the tower in exchange for 'cooperation'.",
    effects: { radioProgress: 1, unlockZones: ["radio_tower_perimeter"], unlockSections: ["factions"] },
  },
  {
    id: "radio_lantern_market",
    pool: "radio",
    weight: 6,
    once: true,
    text: "A trader signal bursts through: three tones, a price, and the smell of kerosene in your head.",
    effects: { radioProgress: 1, unlockSections: ["trader"] },
  },
  {
    id: "radio_orchard",
    pool: "radio",
    weight: 4,
    requires: { radioProgress: 4 },
    once: true,
    text: "A child whispers directions to a place called the Glass Orchard, then laughs when you repeat it back.",
    effects: { secretProgress: 1, unlockZones: ["glass_orchard"] },
  },
  {
    id: "radio_bunker_breath",
    pool: "radio",
    weight: 4,
    requires: { radioProgress: 4, items: ["relay_key"] },
    once: true,
    text: "A sealed channel opens for half a second. Air pumps. Concrete. Someone says 'breach team'.",
    effects: { secretProgress: 1, unlockZones: ["hidden_bunker_entrance"] },
  },
  {
    id: "radio_dead_static",
    pool: "radio",
    weight: 2,
    requires: { secretProgress: 3, items: ["bunker_pass"] },
    once: true,
    text: "The pattern resolves: the static was never random. It was a command layer talking through the dead.",
    effects: { radioProgress: 2, secretProgress: 1, setFlags: { worldReveal: true } },
  },
  {
    id: "radio_civic_hiss",
    pool: "radio:civic_band",
    weight: 6,
    text: "A public-address hiss keeps swallowing whole street names, but not the fear in the speaker's voice.",
    effects: { resources: { reputation: 1 } },
  },
  {
    id: "radio_civic_clip",
    pool: "radio:civic_band",
    weight: 4,
    text: "A clipped dispatch lists shelter capacities that were already overrun when the message was sent.",
    effects: { condition: -1, resources: { morale: 1 } },
  },
  {
    id: "radio_tower_pulse",
    pool: "radio:tower_grid",
    weight: 6,
    text: "The tower grid coughs up a maintenance pulse that sounds more recent than it has any right to be.",
    effects: { resources: { electronics: 1 } },
  },
  {
    id: "radio_tower_ghost",
    pool: "radio:tower_grid",
    weight: 4,
    text: "Someone on the relay net says your district name, waits, and never repeats it.",
    effects: { resources: { reputation: 1 }, condition: -1 },
  },
  {
    id: "radio_sublevel_drain",
    pool: "radio:sublevel_echo",
    weight: 6,
    text: "Pumps cycle somewhere under the streets and the band catches every heavy breath of them.",
    effects: { resources: { parts: 1 } },
  },
  {
    id: "radio_sublevel_steps",
    pool: "radio:sublevel_echo",
    weight: 4,
    text: "Concrete steps count themselves off on the receiver, as if someone is still taking inventory below.",
    effects: { condition: -1, resources: { morale: 1 } },
  },
  {
    id: "radio_anomaly_bloom",
    pool: "radio:anomaly_trace",
    weight: 6,
    text: "The signal blooms into a perfect carrier for half a second, then collapses back into living static.",
    effects: { resources: { relics: 1 } },
  },
  {
    id: "radio_anomaly_voice",
    pool: "radio:anomaly_trace",
    weight: 4,
    text: "A child's voice asks whether the city still remembers its own emergency codes, then laughs when you answer.",
    effects: { condition: -2, resources: { morale: 1 } },
  },
  {
    id: "zone_ruined_bus",
    pool: "zone:ruined_street",
    weight: 6,
    text: "Inside a crushed bus, someone left a toolkit under the driver's seat.",
    effects: { resources: { parts: 2 } },
  },
  {
    id: "zone_ruined_market",
    pool: "zone:ruined_street",
    weight: 4,
    text: "A shattered market stall still has beans sealed behind warped metal.",
    effects: { grantItems: { canned_beans: 1 } },
  },
  {
    id: "zone_apartment_note",
    pool: "zone:burned_apartments",
    weight: 5,
    text: "A soot-black family note says the noise came before the bite.",
    effects: { resources: { morale: 1 }, radioProgress: 1 },
  },
  {
    id: "zone_apartment_cache",
    pool: "zone:burned_apartments",
    weight: 5,
    text: "A bathtub cache gives up medicine and a dry roll of bandages.",
    effects: { resources: { medicine: 1 }, grantItems: { bandage_roll: 1 } },
  },
  {
    id: "zone_gas_siphon",
    pool: "zone:abandoned_gas_station",
    weight: 6,
    text: "You find a tank with enough fumes left to count.",
    effects: { resources: { fuel: 2 } },
  },
  {
    id: "zone_gas_trader_mark",
    pool: "zone:abandoned_gas_station",
    weight: 4,
    text: "Someone marked the wall with lantern symbols and a price code.",
    effects: { resources: { reputation: 1 }, unlockSections: ["trader"] },
  },
  {
    id: "zone_tunnel_case",
    pool: "zone:flooded_tunnel",
    weight: 5,
    text: "A waterproof case is wedged in the concrete seam.",
    effects: { resources: { ammo: 2, parts: 1 }, discoverResources: ["ammo"] },
  },
  {
    id: "zone_tunnel_key",
    pool: "zone:flooded_tunnel",
    weight: 4,
    once: true,
    text: "Behind a service hatch: a relay key in an oilskin pouch.",
    effects: { grantItems: { relay_key: 1 }, secretProgress: 1 },
  },
  {
    id: "zone_hospital_archive",
    pool: "zone:hospital_wing",
    weight: 5,
    text: "Triage logs mention patients responding to frequencies before symptoms.",
    effects: { resources: { medicine: 2, chemicals: 1 }, radioProgress: 1, discoverResources: ["chemicals"] },
  },
  {
    id: "zone_hospital_crash_cart",
    pool: "zone:hospital_wing",
    weight: 4,
    text: "A crash cart still rolls. So does your luck.",
    effects: { resources: { medicine: 1, chemicals: 1 }, discoverResources: ["chemicals"], grantItems: { bandage_roll: 1 } },
  },
  {
    id: "zone_tower_scope",
    pool: "zone:radio_tower_perimeter",
    weight: 5,
    text: "A sniper nest overlooks streets you have already learned the hard way.",
    effects: { grantItems: { tower_rifle: 1 }, resources: { reputation: 1 } },
  },
  {
    id: "zone_tower_field",
    pool: "zone:radio_tower_perimeter",
    weight: 4,
    text: "The fence hum becomes words when you stand too close to it.",
    effects: { secretProgress: 1, resources: { relics: 1 } },
  },
  {
    id: "zone_orchard_reflection",
    pool: "zone:glass_orchard",
    weight: 6,
    text: "Every glass tree shows you somewhere else in the city, all at once.",
    effects: { resources: { relics: 1, morale: 1 }, grantItems: { odd_relic: 1 } },
  },
  {
    id: "zone_bunker_door",
    pool: "zone:hidden_bunker_entrance",
    weight: 5,
    once: true,
    text: "The concrete door opens a hand's width and exhales cold filtered air.",
    effects: { grantItems: { bunker_pass: 1 }, secretProgress: 1 },
  },
  {
    id: "zone_bunker_truth",
    pool: "zone:hidden_bunker_entrance",
    weight: 3,
    once: true,
    requires: { items: ["bunker_pass"] },
    text: "Inside, a dead operations wall shows the project name: DEAD STATIC. Signal suppression. Crowd obedience. Outbreak contingency.",
    effects: { setFlags: { worldReveal: true }, radioProgress: 2, secretProgress: 1, unlockZones: ["glass_orchard"] },
  },
];
